### ISSUE TITLE
Color Palette IDEA/REQUEST

### ISSUE THREAD

**Issue by brimwats1** [jdanielmourao/obsidian-sanctum#102]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when... i have to spend a lot of time adding CSS to override your amazing theme in order to make it follow [Gruvbox](https://github.com/morhetz/gruvbox)/[Solarized](https://ethanschoonover.com/solarized/) colors (joking here, if it's not clear :) )

**Describe the solution you'd like**
A gruvbox palette option? I saw it on the roadmap.

**Describe alternatives you've considered**
Continuing to add overrides to my own CSS

**Additional context**
The most recent sanctum updated added a looooot of new color things that I had to hackily override, so that's the inspiration here! I'm happy to provide my CSS for you to work from

**Comment by jdanielmourao** [comment]
Changing the primary colours of the theme isn't a big issue, although changing every other colour might be a bit hard and tedious to do, I admit, mainly because I use SCSS variables for those. I reckon I can just change those into CSS custom properties, and it will make your life much easier, only having to change those in `:root` and the whole theme will change.

**Comment by brimwats** [comment]
that was my thought too! I suspect it's much easier for me to tweak SCSS colors via style settings

**Comment by jdanielmourao** [comment]
> that was my thought too! I suspect it's much easier for me to tweak SCSS colors via editing or overriding root or via style settings.

Just wanted to let you know that with the new update, all the palette colours are available as custom properties. I'll probably have to still insert them in some places, but should now be easier to customize it via snippets.

**Comment by jdanielmourao** [comment]
Closing this for now. In case you haven't caught it, there are now options to customize the theme, either by presets or more granular control. There's not a direct way of adding specific colours, but I think you can still get some satisfying results, imo.
