### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by sberbec** [jdanielmourao/obsidian-sanctum#105]
A toggle feature for the floating reading/editing action button on the new Sanctum update. I will say it's growing on me... But my preference is for it to remain in the header. 

Thanks so much!

**Comment by jdanielmourao** [comment]
Just writing a reply to tell you that I've added this to the Roadmap.

**Comment by jdanielmourao** [comment]
As this was added in the latest release, I'll go ahead and close the issue.
