### ISSUE TITLE
[BUG] Text selection doesn't follow chosen accent colour

### ISSUE THREAD

**Issue by lkadre** [jdanielmourao/obsidian-sanctum#110]
**Describe the bug**
The new choices of accent colours are great! However, I immediately noticed that the colours don't apply to text selection, where it's still (what i assume) the default colour (teal?). 

**To Reproduce**
Choose different accent colours on Style Settings. Then, select any text on any note.

**Expected behavior**
The text selection would be in the colour of the chosen accent colour from Style Settings.

**Screenshots**

<img width="428" alt="Screen Shot 2022-01-06 at 17 27 16" src="https://user-images.githubusercontent.com/66343542/148447099-ca85178c-b8be-4bf9-a4e2-7ccccbfd571f.png">
<img width="519" alt="Screen Shot 2022-01-06 at 17 28 20" src="https://user-images.githubusercontent.com/66343542/148447238-b26e99a0-d595-47d8-a236-4edd2f78ddae.png">

**Version [Desktop or Mobile]:**
Desktop, Mac

**Editor**
CM6, Live Preview

**Additional context**
N/A, but I'm happy to provide more context if it helps!

**Comment by jdanielmourao** [comment]
I tried to sync it with the accent colour, but since text-selection colour works best with an opacity value, it made things hard in Style Settings. I managed to make it work, but then it was broken for anyone not using Style Settings. I'll probably just add a separate option for it. Thanks for pointing it out! 🙂

**Comment by jdanielmourao** [comment]
![Obsidian_lb3GUSmEom](https://user-images.githubusercontent.com/91087143/148455638-1ea6cb72-a314-4551-be34-851d924b4bad.gif)

Will be added next update!

**Comment by lkadre** [comment]
Nice!! Thank you!
Otherwise I was going to suggest keeping it grey for simplicity/consistency regardless of chosen accent colour, but this looks great <3

**Comment by lkadre** [comment]
(Sorry, accidentally closed the issue lmao)

**Comment by jdanielmourao** [comment]
If everything's ok now that the feature was added, I'll go ahead and close the issue :)
