### ISSUE TITLE
[BUG] Relationship lines in edit view are not working

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#111]
This is what relationship lines in the editing view looks like for me with the latest update. 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/73867063/148460085-63429d89-eecc-4158-ac41-83b33659cde4.png">

**Comment by jdanielmourao** [comment]
Try updating Obsidian's installer. Even if you have the most recent version, sometimes you need to update the installer for some functionalities to be supported. There have been a few cases lately where that seemed to do the trick.

**Comment by kmaustral** [comment]
Updating the installer fixes the problem, thank you. I had thought you just needed to update from within the app. I will remember this as a future troubleshooting option.
