### ISSUE TITLE
[BUG] Line appears through indented lists

### ISSUE THREAD

**Issue by agryson** [jdanielmourao/obsidian-sanctum#112]
**Describe the bug**
Nested items (nested bullets, nested checkboxes) create an offset line that cuts down the whole page in edit mode

**To Reproduce**
1. Enter edit mode
2. Create a checklist item or bullet point
3. Go to next line and create another
4. Indent it (tab)

**Expected behavior**
Either:
a) Indentation with no visual artefacts (preferred option)
or
b) the line should be aligned left full with respect to the parent (left of the bullet point or checkbox) and only extend down vertically to the bottom of any child items in the sub list, no further.

**Screenshots**
![Sanctum Issue](https://user-images.githubusercontent.com/1445853/148517830-56c5dddc-52c7-4abc-b11e-6b7406d62629.gif)

Removing the `background-image` line from `.cm-hmd-list-indent::before` resolves the issue for me.
![image](https://user-images.githubusercontent.com/1445853/148518416-3cff91fd-58ce-49aa-ac18-5f21df6f985e.png)

**Version [Desktop or Mobile]:**
- Obsidian: v0.13.19
- Sanctum: 0.5 (according to the css file in themes but I updated to latest before writing)

**Editor**
I don't know but tell me how to find out and I will update this issue.

**Additional context**
I use vim mode with dark version of theme. I do use Style Settings plugin but have only edited accent colors with it.

**Comment by jdanielmourao** [comment]
Hi! You'll have to update the installer. For doing that, simply go to [obsidian.md](https://obsidian.md) and install again, it will take care of installing the latest installer version on top of your current one. That should fix that problem.

**Comment by agryson** [comment]
🤔ok, here's the result after reinstall :
![image](https://user-images.githubusercontent.com/1445853/148556969-c5dacf14-1b08-4bf2-a71b-c23325202a9a.png)
 so we can consider this fixed.
 
Here were my versions before reinstall though: 
![image](https://user-images.githubusercontent.com/1445853/148556698-9a0e7ded-af87-4da7-ad0e-835e5d122775.png)
Obsidian claimed that everything was up to date, is this something that will happen often? (perhaps out of your remit - but would you advise a reinstall on every update, or should I create a ticket at Obsidian?)

**Comment by jdanielmourao** [comment]
It shouldn't happen often. From what I could gather from a conversation with the devs over on discord, it's because the installer comes with the base electron executable, which includes chromium/node, and Obsidian's auto updater. Sometimes, even though Obsidian's up-to-date, since the installer is older, it might have an older version of Chromium, which doesn't support some CSS features yet, in this particular case, `overflow-y: clip`.

**Comment by jdanielmourao** [comment]
I'd probably update the installer every few updates just to make sure something like this doesn't happen. Although, to be fair, usually the devs put a disclaimer on updates, so people know they should update the installer.

**Comment by agryson** [comment]
Great, thanks for the explanation, I'll try to make it a habit to reinstall when I see chrome has updated, should keep things better aligned. 👍
