### ISSUE TITLE
[BUG] Tag suggestions are not positioned correctly

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#113]
**Describe the bug**
The tag suggester popup is not displaying correctly when we being to type the tag (`#abcd`)

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Go to a file
2. start typing a tag
3. notice that the tag suggestions are not dispaying under cursor but rather at the top left corner of Obsidian WIndow.
![image](https://user-images.githubusercontent.com/68785729/149079481-ce1da3ac-db13-48cc-b61d-aec8eb6e7afa.png)

**Expected behavior**
Tag suggestions should be displayed under the cursor.
![image](https://user-images.githubusercontent.com/68785729/149079449-3b86eade-c47f-4f7d-9779-3218f49d8ab1.png)

**Version [Desktop or Mobile]:**
Everything updated.

**Comment by eleanorkonik** [comment]
hah I noticed this today too and was planning to report it. Thanks!

**Comment by jdanielmourao** [comment]
Pushed a fix for this!
