### ISSUE TITLE
[BUG] Conflict with indentation guides plugin

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#115]
**Describe the bug**

Indentation lines cuts into the admonitions css class boxes

![image](https://user-images.githubusercontent.com/75856959/149367500-a5d2e674-a00a-499c-b8f8-31d430a24f67.png)

Desktop, on the latest everything, and yes I know Sanctum has indentation guides already I just was testing stuff 🙈

**Comment by jdanielmourao** [comment]
The plan will be to get the indentation guides plugin to look like the ones that are currently in the theme, although I still have to get that working like I want it to.

**Comment by eleanorkonik** [comment]
sounds good! Just wanted to do my part and report it 💚

**Comment by jdanielmourao** [comment]
Closing this since as of the latest update, there's compatibility with the Indentation Guides plugin
