### ISSUE TITLE
[BUG] Alternate checkboxes are not rendering inside admonition during editing mode

### ISSUE THREAD

**Issue by amandarolia** [jdanielmourao/obsidian-sanctum#118]
**Describe the bug**
- Sanctum theme have some alternate checkboxes. They are not rendering inside admonition.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Insert admonition block
2. Insert - [?] Hello world inside admonition block 
3. Get outside of admonition block
4. Hit enter

**Expected behavior**
- It will show ? in form of emoji but it showing green tick
**Screenshots**
![image](https://user-images.githubusercontent.com/42024438/149539655-46747344-9397-4bdf-9d51-7a6a9929b98b.png)

**Version [Desktop or Mobile]:** Desktop

**Editor**
CM6 Editor

**Additional context**

**Comment by jdanielmourao** [comment]
Try updating to the latest version. This has been fixed. :)
