### ISSUE TITLE
[BUG] Highlighting not showing on mobile

### ISSUE THREAD

**Issue by dancemonkey** [jdanielmourao/obsidian-sanctum#119]
When placing "==" around text the highlighting does not render on the mobile (iOS) client. The same text renders fine on desktop.

**Screenshots**
Desktop Windows 10 screen:
![image](https://user-images.githubusercontent.com/9327646/149546265-52b3750c-61ca-41d3-8e6a-bf31b8ab52ae.png)

Mobile Screen:
![image](https://user-images.githubusercontent.com/9327646/149546832-134835b6-3558-4358-bdc1-d8318e330590.png)

**Version [Desktop or Mobile]:**
Mobile version, iOS 15.1.1, Obsidian 1.0.5

**Editor**
CM6 editor on desktop, using only the App Store version on mobile (not insider release)

**Comment by jdanielmourao** [comment]
That is odd. I can't replicate the issue, but I also don't have a mobile iOS device. In any case, I'll be reviewing the entire theme's code, and most likely changing how highlights are displayed, so hopefully it will be fixed next update. :)

**Comment by jdanielmourao** [comment]
With the latest update's changes to highlights, this might not be a problem anymore. Please let me know if there are any changes.

**Comment by dancemonkey** [comment]
That did it, I’m seeing highlights on mobile. Thanks!
