### ISSUE TITLE
[IDEA/REQUEST] Monospaced fonts when composing tables

### ISSUE THREAD

**Issue by danielfilho** [jdanielmourao/obsidian-sanctum#121]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Today, when working with tables on the theme, this is how it looks like:

![CleanShot 2022-01-19 at 10 39 42](https://user-images.githubusercontent.com/24597/150104456-28639bf3-19ff-4506-b858-cb016eea07d2.png)

I believe that it would be much nicer for tabular data to be styled with monospaced fonts, so it would be something like this:

![CleanShot 2022-01-19 at 10 41 22](https://user-images.githubusercontent.com/24597/150104716-5a6082e6-b010-4685-89ab-f7578a7c1913.png)

**Describe alternatives you've considered**
I believe that the best alternative/approach would be using monospaced fonts when composing tables

**Additional context**
Nothing that cross my mind

Please, let me know if I can help in any way. I'll take a look on the code so I can contribute to this if it's the case :)

**Comment by jdanielmourao** [comment]
I can add that.

**Comment by jdanielmourao** [comment]
This has been added in the latest update!
