### ISSUE TITLE
[BUG][ipad] Find modal occupies the whole page

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#123]
**Describe the bug**
The find modal captures the whole page sometimes with no way to come out of it.
**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Go to 'Thee dot menu'
2. Click on 'Find'
3. See error

**Expected behavior**
1. Search reaults
2. A way to come out of it (no space to tap on)

**Screenshots**
![C290168A-64D0-4DC7-BDD6-E4A8CBF0FEC4](https://user-images.githubusercontent.com/68785729/150143128-4f17238a-4a84-4827-a7e3-7d2fcbbf5776.png)

**Comment by jdanielmourao** [comment]
Closed for repeated issue
