### ISSUE TITLE
[IDEA/REQUEST] Remodel the Command/Switcher modal for iOS/iPad/Mobile

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#124]
**Is your feature request related to a problem? Please describe.**
Currently the commands suggester or file select model occupies almost all of the screen which makes it difficult to come out of and and there is no view the notes behind it

**Describe the solution you'd like**
A smaller sleeker modal. (minimal could be an example)

**Describe alternatives you've considered**
**On the minimal theme they look like these:**
Command pallet 
![9D22B156-27B1-4172-9C67-B72E96A54717](https://user-images.githubusercontent.com/68785729/150143738-b17baac9-616f-45ab-abe5-d47ca720e030.jpeg)

Switcher

![C9994ACE-A6FF-4552-875B-153F4CFFADF2](https://user-images.githubusercontent.com/68785729/150144077-bbaccb37-b25e-4bac-927a-92d794dd6bdb.jpeg)

**while on sanctum:** 
Command Pallet 
![BB59E9EC-7C43-40C8-A555-A983D6BD18F0](https://user-images.githubusercontent.com/68785729/150144647-115822dd-cb65-4545-8510-426f9487dbf1.png)

Switcher
![36E76C28-17EB-4144-9A8A-AB54C599820A](https://user-images.githubusercontent.com/68785729/150143922-6ba16752-767f-44da-bac8-7966ced0ae7b.jpeg)

Switcher with full keyboard 
![509C7388-803C-4CA3-BB3C-5B2B07E08296](https://user-images.githubusercontent.com/68785729/150144054-36bbf949-fe5c-4099-af6e-9aeee5ba66f0.jpeg)

**Additional context**

 I guess only the width needs to be adjusted, and maybe the model needs to be centred. 

This is just a suggestion and a request. If possible please consider. 
Love the Theme!!!

**Comment by jdanielmourao** [comment]
This is most likely because I didn't use a @media query specifically targetting tablets, so it shows the solution designed for phones. I'll sort it out. 👍🏻

**Comment by dummifiedme** [comment]
Thanks!!

**Comment by jdanielmourao** [comment]
This has been dealt with in the latest update!
