### ISSUE TITLE
[BUG] Custom checkboxes not working in Reading View

### ISSUE THREAD

**Issue by lkadre** [jdanielmourao/obsidian-sanctum#128]
**Describe the bug**
Custom checkboxes just stopped showing on Reading View with the newest update, both with or without admonitions class. They still work in Live Preview.

**Screenshots**

<img width="583" alt="Screen Shot 2022-01-25 at 21 10 18" src="https://user-images.githubusercontent.com/66343542/151080881-c833069c-70b2-42a5-8558-0986db1dfe6c.png">

<img width="594" alt="Screen Shot 2022-01-25 at 21 10 38" src="https://user-images.githubusercontent.com/66343542/151080907-a68caf87-4ff4-4ae8-80df-e8427a581e9f.png">

**Comment by lkadre** [comment]
Manually installing 0.6.1 restored them, though now they're slightly off. Again, this is just in Reading mode.

<img width="589" alt="Screen Shot 2022-01-25 at 21 23 32" src="https://user-images.githubusercontent.com/66343542/151081997-d1d21a34-bf8b-4b90-b57b-a8e65cd55d0c.png">

**Comment by jdanielmourao** [comment]
I have released a couple hotfixes since the 0.6.1 update. Have you tried updating to those? I'm unable to reproduce that error on my side.

**Comment by lkadre** [comment]
I've updated through the settings.

It seems to only be an issue with a few notes, not all of them... I'll try to figure out what they have in common and get back to you.

<img width="1127" alt="Screen Shot 2022-01-26 at 15 18 54" src="https://user-images.githubusercontent.com/66343542/151222901-c9d80ae9-76af-4034-92aa-6dc32199a2b5.png">

**Comment by lkadre** [comment]
Can you test if you can reproduce with the `- [!]` admonition? When I take it out it works again.

**Comment by jdanielmourao** [comment]
Ah, I see what's going on. I think creating a `loose` list makes the checkboxes disappear.
![Loom_DBytR6nWc0](https://user-images.githubusercontent.com/91087143/151230824-5e4a310a-c7f3-4d45-a4f7-bce2f1e0cc9f.gif)

**Comment by jdanielmourao** [comment]
Loose lists create another tier of hierarchy, so it messes up the code. I'll work on a fix!

**Comment by lkadre** [comment]
Ah you're right! It was the line between the different types that causing the problem. They're just a few notes so I can just delete the line without issue, so no rush!

**Comment by jdanielmourao** [comment]
Just wanted to say that I've managed to fix this, so both custom checkboxes as well as pseudo admonitions will work with loose lists, in the next release.
