### ISSUE TITLE
[BUG] all caps in `[[links]]` breaks a use case

### ISSUE THREAD

**Issue by hinnerk** [jdanielmourao/obsidian-sanctum#130]
On Obsidian 0.13.23 with Sanctum 0.6.1:

`[[Wikilinks]]` are shown in caps which make it impossible to tell which file is linked.

Example:

<img width="276" alt="Bildschirmfoto 2022-01-29 um 13 07 33" src="https://user-images.githubusercontent.com/24145/151660565-b9d81bf0-3056-48c9-9558-508bb31359da.png">

it is impossible to know which file is linked on file systems that respect capitalization:

- `some_file_or_other.jpg`
- `some_file_or_other.JPG`
- `SOME_FILE_OR_OTHER.JPG`
- `Some_File_or_Other.JPG`
- …

**Expected behavior**

To see the precise name of the linked file or note.

**Comment by jdanielmourao** [comment]
Hi! There will be an option next release which will enable you to toggle off the 'small caps' links. Should be released in the next few days.

**Comment by hinnerk** [comment]
Thank you for your quick and helpful response!

**Comment by jdanielmourao** [comment]
The option should be available with the latest update! :)
