### ISSUE TITLE
[IDEA/REQUEST] Italic font weight

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#131]
**Is your feature request related to a problem? Please describe.**
The *italic* text doesn't have the same weight as the rest, is it intentional?

**Describe the solution you'd like**
Having the italic and normal text have the same font-weight

**Describe alternatives you've considered**
Change the font

**Comment by jdanielmourao** [comment]
It is intentional, mainly because I didn't consider a simple italic style enough of a difference.

**Comment by TRENEEDANAME** [comment]
Ok, thank for the precision
