### ISSUE TITLE
[BUG] Background blur option is reversed

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#132]
**Describe the bug**
The "No background blur" options in Style setting's setting is inverted

**Expected behaviour**
the option is toggled (should mean no background blur) = background blur
the option is not toggled (should mean background blur) = no background blur
They are reversed

**Screenshots**
"No background blur" is ticked
![image](https://user-images.githubusercontent.com/79509045/151697003-c1621dcf-46ce-458c-ac23-18964b60f154.png)

"No background blur" is off
![image](https://user-images.githubusercontent.com/79509045/151697035-a76c844e-ac13-4bb3-ab9c-3deb1a136e86.png)

**Version [Desktop or Mobile]:**
Desktop (Linux, AUR version)

**Editor**
New Live Preview

**Comment by jdanielmourao** [comment]
I'm not sure what you mean. If you toggle it, it disables background blur, as the option itself implies. Toggles are bidimensional. If you toggle it, you get the option, if you don't, it's disabled.
