### ISSUE TITLE
[IDEA/REQUEST] square shaped checkboxes

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#133]
**Is your feature request related to a problem? Please describe.**
Is it possible to bring back the square shaped checkboxes ? I really liked them.

**Describe the solution you'd like**
Maybe add it as an option in style setting ?

**Comment by jdanielmourao** [comment]
That should be easy enough to do.

**Comment by TRENEEDANAME** [comment]
I also have the squared checkbox. Idk why (Android version, last update)

**Comment by jdanielmourao** [comment]
> I also have the squared checkbox. Idk why (Android version, last update)

You should update the theme. I fixed that in a hotfix.

**Comment by jdanielmourao** [comment]
This has been added as a SS option in version 0.6.3
