### ISSUE TITLE
[BUG] Misaligned button - Sliding Panes Plugin

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#135]
On the sliding panes plugin, the close button on active pane is misaligned. 

![Peek 2022-02-01 19-42](https://user-images.githubusercontent.com/68785729/151984745-12df974c-fbab-4e56-a1fa-39836ff4ad00.gif)

**Comment by dummifiedme** [comment]
I noticed the same issue with Default theme, so closing this issue.
If you anyway found the error somewhere, do tag me :)

Unsolved still.

**Comment by jdanielmourao** [comment]
Can't reproduce the issue on my end.
