### ISSUE TITLE
[BUG] Visibility of Buttons on iOS/iPad 

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#136]
The buttons on all the modals on iPad are not visible in Dark Mode. 
![image](https://user-images.githubusercontent.com/68785729/151985081-edb98424-110f-48ef-a28e-f6261b4764a6.png)

**Comment by bladecoates** [comment]
Confirmed as well, using True Dark.

**Comment by jdanielmourao** [comment]
I'd update the theme to version 0.6.3, where this has been fixed.
