### ISSUE TITLE
[BUG] Unordered list's line are in the line number (buffer)

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#137]
**Describe the bug**

**To Reproduce**
Use the "Live Preview"
Do unordered list
Press tab (need to have a certain style settings' setting, can't find it)
The lines are in the buffer (line number)

**Expected behaviour**
The relationships line should be under the list

**Screenshots**
![image](https://user-images.githubusercontent.com/79509045/152231983-00b09465-2781-4be1-9d1f-42c57dbdfe6d.png)

**Version [Desktop or Mobile]:**
Desktop (Linux, AUR), latest version of Obsidian and the themes/plugins

**Editor**
New live editor

**Additional context**
None, if you need more info, I will be happy to provide them

**Comment by jdanielmourao** [comment]
I'd try to update both the theme and the Indentation lines plugin. It might be a plugin issue, since I only change the default values so people don't have to tweak them in style settings.

**Comment by jdanielmourao** [comment]
This might also be the new Outliner indentation lines css interfering with things. I'd toggle off 'draw vertical indentation lines' if that were the case.
