### ISSUE TITLE
[BUG] buttons not visible on MacOS after changing Dark Mode Accent Color in Style Settings plugin

### ISSUE THREAD

**Issue by dsteinbock** [jdanielmourao/obsidian-sanctum#138]
**Describe the bug**

When I use Style Settings plugin to change Dark Mode Accent Color to anything but the default Teal, my UI buttons turn dark grey text on dark grey background. I reproduced this in the Obsidian Help vault, no snippets or plugins.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Activate Sanctum theme in Dark Mode with default styling and no CSS snippets
2. Open Style Settings plugin and change Dark Mode Accent Color to Pink
3. Click Community Plugins in settings and notice that the UI buttons are dark grey text on dark grey background

**Expected behavior**

Button background should be the selected accent color

**Screenshots**

![Screen Shot 2022-02-02 at 8 07 30 PM](https://user-images.githubusercontent.com/4734875/152280278-89170ddd-d226-4436-a47b-d6a1db2e3d95.png)

**Version [Desktop or Mobile]:**
Desktop v0.13.23

**Editor**

New editor

**Additional context**

**Comment by jdanielmourao** [comment]
I can reproduce the issue. I've been taking a few days off from coding, but I'll get back in the coming couple days, so I'll probably release a small bug fixing update.

**Comment by dsteinbock** [comment]
Thanks - that fixed it for the default install. However my own Style Settings snippet for changing dark accent color still produces the blank buttons. I'm trying to pick a custom accent color because I find the presets too muted. But there seems to be an incompatibility with how you implement accent colors. The following snippet uses custom color picker but produces the blank buttons bug. Do you have an additional CSS snippet that might protect the buttons from getting messed up like this, or another suggestion or fix?

```
/* @settings

name: Sanctum DS tweaks
id: ds-sanctum
settings:
	-		
		id: color-accent-d
		title: DS Dark Mode Accent Color
		type: variable-color
		format: rgb-values
        	default: rgb(255, 51, 190)
*/
```

**Comment by dsteinbock** [comment]
I found a CSS solution. I copied the button CSS code from your theme and modified slightly in the following snippet. I simply changed the Alpha channel syntax from slash format `/0.9` to the older comma format `, 0.9`. Perhaps Obsidian and/or Style Settings doesn't fully support the slash syntax.

```
.theme-dark button.mod-cta {
    font-weight: var(--font-medium);
    background-color: rgba(var(--color-accent-d), 1.0);
    border: 1px solid var(--color-primary-0);
    box-shadow: 0px -1px 0px 0px rgba(8, 8, 8, 0.3) inset, 0 1px 3px 1px rgba(0, 0, 0, 0.1);
}

.theme-dark button.mod-cta:hover {
  background-color: rgba(var(--color-accent-d), 0.9);
}
.theme-dark button.mod-cta:active {
  background-color: rgba(var(--color-accent-d), 1.0);
  box-shadow: 0px -1px 0px 0px rgba(8, 8, 8, 0.2) inset, 0px 1px 3px 1px rgba(8, 8, 8, 0.3) inset;
}
```
