### ISSUE TITLE
[BUG] Small select pin/toggle 

### ISSUE THREAD

**Issue by dummifiedme** [jdanielmourao/obsidian-sanctum#140]
I don't exactly what it is called. I am referring to the small tiny dots in front of "Parent" and "Ministry".
They are not clearly visible as to on or off (ticked or not)

On Sanctum:
![image](https://user-images.githubusercontent.com/68785729/152760482-eebcbb58-e9a6-42db-bbb9-d58217fa0acb.png)

On Default
![image](https://user-images.githubusercontent.com/68785729/152760787-101b77f6-f975-409a-8b28-fa17a8448323.png)

**Comment by lguenth** [comment]
+1 for this request, this type of "checkbox" which also comes up in plugin modals is really hard to see and click

**Comment by jdanielmourao** [comment]
I have a fix for this that will come next release! Make sure to check if there's an update available :) Sorry for the wait

**Comment by jdanielmourao** [comment]
It has been fixed. I recommend updating to the latest version of Sanctum! :)
