### ISSUE TITLE
[BUG] Tag with underscores is styled as two separate tags

### ISSUE THREAD

**Issue by beetrootpaul** [jdanielmourao/obsidian-sanctum#141]
**Describe the bug**

**To Reproduce**

1. Type `#valid_tag_with_underscores` in your note
2. Observe how it is styled as two tags one after another: `#valid_tag_with_` and `#underscores`

**Expected behavior**

Tag styled as as a single one: `#valid_tag_with_underscores`

**Screenshots**

<img width="335" alt="screenshot 2022-02-09 at 17 12 56" src="https://user-images.githubusercontent.com/92947323/153242318-6312c0c5-765b-4ebd-8143-b5bc53f57055.png">

**Version [Desktop or Mobile]:**

- Obsidian macOS v0.13.23 from installer v0.13.19
- Sanctum v0.6.2

Following Style Settings for Sanctum:
```json
{
  "sanctum@@light-mode-palette": "sanctum-light",
  "sanctum@@dark-mode-palette": "sanctum-coldgrey-d",
  "sanctum@@head-indicator": true,
  "sanctum@@head-indicator-active": false,
  "sanctum@@heading-1": "2.5rem",
  "sanctum@@heading-2": "2.0rem",
  "sanctum@@heading-3": "1.5rem",
  "sanctum@@heading-4": "1.25rem",
  "sanctum@@heading-5": "1.00rem",
  "sanctum@@dim-panes": false,
  "sanctum@@tasks": true,
  "sanctum@@hr-options": "default",
  "sanctum@@edit-mode-tasks": true,
  "sanctum@@table-options": "default",
  "sanctum@@alt-link": false,
  "sanctum@@no-titlebar-title": true,
  "sanctum@@show-yaml": false,
  "sanctum@@topside-status-bar": true,
  "sanctum@@compact-outline": true,
  "sanctum@@note-title-left": true,
  "sanctum@@show-vault-name": false,
  "sanctum@@left-nav-arrows": true,
  "sanctum@@settings": 60,
  "sanctum@@community-theme": 90,
  "sanctum@@community-plugin": 90,
  "sanctum@@no-blur": false,
  "sanctum@@no-sanctum-icons": false
}
```

**Editor**

Bug can be observed in both legacy (the one I use on a daily basis) and new editors in the editing mode. Not present in the red mode.

**Comment by beetrootpaul** [comment]
Now I realised the same happens for a default Obsidian theme too, it was just not clearly apparent. On the screenshot below you can see how tag is broken into two parts (I have added some CSS to make it visible). My question is then: where to report it?

<img width="1504" alt="screenshot 2022-02-09 at 19 58 35" src="https://user-images.githubusercontent.com/92947323/153271120-0517519d-0f2c-4b07-85bb-075d2c70fb27.png">

**Comment by jdanielmourao** [comment]
So I have noticed! You can report it in the obsidian forums, although I've made somewhat of a fix for it.
<img width="179" alt="Loom_03uXhy7C6B" src="https://user-images.githubusercontent.com/91087143/153272503-20d0fa03-fe9b-4eab-9e1c-59bc8199c774.png">

**Comment by beetrootpaul** [comment]
Now I again think it doesn't have to be an issue on the Obsidian side. Why? Because the last HTML element of the tag contains extra `cm-hashtag-end` class which could allow to improve CSS styling to capture the whole tag, I suppose.

Also, I see it's styled better in "Things" theme:
<img width="626" alt="screenshot 2022-02-09 at 23 25 53" src="https://user-images.githubusercontent.com/92947323/153300923-d56c8f33-4e07-49e8-bde1-fb039987a17a.png">

> although I've made somewhat of a fix for it.

I see it now! Thanks for your commit and release! I updated locally and it works great now ❤️
