### ISSUE TITLE
[BUG] IA Writer font not displayed

### ISSUE THREAD

**Issue by ubuntudroid** [jdanielmourao/obsidian-sanctum#143]
**Describe the bug**
Documentation says the iA Writer fonts come bundled with this plugin. However, for me the iA Writer font isn't displayed - it isn't even referenced in the default font settings when checking using Style Settings.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Install the plugin
2. Check the displayed font, it isn't iA Writer Quattro.

**Expected behavior**
iA Writer font is used throughout the Obsidian after installing the plugin.

**Version [Desktop or Mobile]:**
0.13.23

**Editor**
new editor

**Additional context**
I managed to work around this by manually installing the font and referencing from the font settings, but that's not what should be necessary, right?

**Comment by jdanielmourao** [comment]
Hi! There was an error when trying to commit a README change, so the iA Writer was still mentioned, despite having been discontinued from the default theme. It is, however, still available as a snippet, which you can find [here](https://github.com/jdanielmourao/obsidian-sanctum/blob/main/snippets/iA_Writer_S.css).

**Comment by ubuntudroid** [comment]
Got it! Is there a reason why you went with the IBM font instead of the iA Writer one?

**Comment by jdanielmourao** [comment]
Imho, IBM works better for User Interface, looks tighter whilst bringing a bit of personality as well, and showcases white space much better. iA Writer can still be enjoyable to write with, and is based on IBM Plex, hence why I kept a snippet for it (they don't clash too much).
