### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheTobiasRieper** [jdanielmourao/obsidian-sanctum#144]
On the IPad, In the sliding panes(Andy’s Mode) community plug-in the headings of the panes we are not in disappears. 
![IMG_5540](https://user-images.githubusercontent.com/99830363/154973062-ab28221d-09a0-46b5-8d25-cd1de176c966.jpeg)

**Comment by jdanielmourao** [comment]
I haven't been able to reproduce this issue atm. Will keep an eye on it

**Comment by jdanielmourao** [comment]
This shouldn't be an issue in the latest release of Sanctum for Obsidian 0.16.x. If you don't have an Insider License, and thus access to the insider build of Obsidian, you'll probably have to wait a bit more, but I expect that version of Obsidian to be available to the general public in the coming weeks.
