### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheTobiasRieper** [jdanielmourao/obsidian-sanctum#145]
On the iPad version we are not able to scroll all the way down in the file explorer
![IMG_5507](https://user-images.githubusercontent.com/99830363/154973469-3c6a2f86-bec5-448a-83b2-ab25cc88e4e2.gif)
r
![IMG_5506](https://user-images.githubusercontent.com/99830363/154973513-7a30d5ba-b92c-4bad-82fc-c7c9708ff0e3.jpeg)

it doesn’t let me scroll all the way down to select the note

**Comment by se-cung-syu-ngai** [comment]
This is also an issue for me. Current workaround: have a few files name zzz, zzzz, zzzzz, etc. to act as filler.

**Comment by jdanielmourao** [comment]
I've added some bottom padding on mobile to hopefully fix the issue. Do get back to me if you feel like it needs more/less of it.
