### ISSUE TITLE
Title bar issue with screen splitting

### ISSUE THREAD

**Issue by albfaggion** [jdanielmourao/obsidian-sanctum#146]
![IMG_1062](https://user-images.githubusercontent.com/87950446/155891342-add03cb7-67b3-4512-846d-4e14aee1e4a2.png)

**Comment by albfaggion** [comment]
I’ve had this issue with the title bar in the inactive panel when I split the screen on the iPad.

**Comment by jdanielmourao** [comment]
I haven't been able to reproduce this issue, but will keep an eye out for it in case something changes.

**Comment by jdanielmourao** [comment]
This shouldn't be an issue in the latest release of Sanctum for Obsidian 0.16.x. If you don't have an Insider License, and thus access to the insider build of Obsidian, you'll probably have to wait a bit more, but I expect that version of Obsidian to be available to the general public in the coming weeks.
