### ISSUE TITLE
Letters in links going to the next line

### ISSUE THREAD

**Issue by albfaggion** [jdanielmourao/obsidian-sanctum#147]
I don't know if I've described the issue properly, but you can see it here. It happens all the time on all my devices. 
![D2685BBF-EE01-4113-87B5-D126708F581A](https://user-images.githubusercontent.com/87950446/155900217-3acae0b4-8602-4aad-82b9-74355ecde836.png)

**Comment by badjerphoenix** [comment]
This happens to me all the time as well. Especially when I am at work where I need to use my mobile device

If this were fixed I would seriously take a deep dive into this theme. Love everything else that I am seeing so far

**Comment by jdanielmourao** [comment]
I believe I have found a simple fix for it. Check for updates :)

**Comment by albfaggion** [comment]
Thank you for this, and your beautiful theme. I'll check it.
