### ISSUE TITLE
[IDEA/REQUEST] Options for code blocks

### ISSUE THREAD

**Issue by Mobuos** [jdanielmourao/obsidian-sanctum#148]
**Is your feature request related to a problem? Please describe.**
When looking over notes with code blocks, their edges get... let's say, blurry. It's hard to quickly glance over and see "Yes there are 3 code blocks here", and overall I feel like the appearence of the code blocks could be different.
![image](https://user-images.githubusercontent.com/12601762/156217486-996f3070-2379-492e-abbd-96018a4898f4.png)

**Describe the solution you'd like**
I would like options in the Style settings referring to code blocks. Adding a border, a background color, I don't know.

**Describe alternatives you've considered**
I don't know, I tried adding "---" to indicate code blocks but that doesn't look right as well

**Additional context**
And just in case something on my end is broken, the code blocks look like colorful text with no background or border, in a smaller size, right?

**Comment by jdanielmourao** [comment]
I recommend updating to the latest version of Sanctum, as it seems to be working fine. I'd like to know if you've noticed any changes.

**Comment by Mobuos** [comment]
> I recommend updating to the latest version of Sanctum, as it seems to be working fine. I'd like to know if you've noticed any changes.

Just updated it now and... It looks the same 😬

On edit mode it shows a white background, but on reading it's still without one.

**Comment by jdanielmourao** [comment]
Alright, please try again. I've made an update.

**Comment by Mobuos** [comment]
Still nothing...
Dark theme shows it but light theme stays the same.

**Comment by jdanielmourao** [comment]
> Still nothing... Dark theme shows it but light theme stays the same.

I'm currently working on Sanctum's version for the upcoming Obsidian 0.16.x update. Hopefully you won't see this issue anymore, especially considering that I'm rewriting the whole theme from scratch.

> I hope this would apply to `inline code` as well!
> 
> That would be awesome!
What do you mean by this exactly?

**Comment by cabbott008** [comment]
Thank you so much for all your hard work! I look forward to using this theme once `inline code` is able to be configured for better background contrast and font styling. 

The options you already provide are impressive!

**Comment by jdanielmourao** [comment]
This shouldn't be an issue in the latest release of Sanctum for Obsidian 0.16.x. If you don't have an Insider License, and thus access to the insider build of Obsidian, you'll probably have to wait a bit more, but I expect that version of Obsidian to be available to the general public in the coming weeks.

**Comment by cabbott008** [comment]
Your speed of regular updates is very impressive! 

I do have the Insider License (0.16.2) and also updated to your update made just moments ago and restarted Obsidian.

I couldn't find a new option for things pertaining to `inline code` within the Style Settings plugin. I scoured all available setting for thoroughness.

Am I missing something?

**Comment by jdanielmourao** [comment]
> Your speed of regular updates is very impressive!
> 
> I do have the Insider License (0.16.2) and also updated to your update made just moments ago and restarted Obsidian.
> 
> I couldn't find a new option for things pertaining to `inline code` within the Style Settings plugin. I scoured all available setting for thoroughness.
> 
> Am I missing something?

Currently the only setting that also affects inline code in in `Code Blocks -> Code borders` . The issue with not being able to see the background color of inline code or code blocks, though, isn't present anymore. I'm also considering including inline code in the `Syntax Highlighting color scheme` option.

**Comment by cabbott008** [comment]
Ah. It's subtly perhaps then is why have yet to discern a difference with `inline code` produced by any currently available options. Having said that, the changes, of course, with full code blocks is very obvious.

My individual desire would be to be able to change the following with `inline code`, in order of priority:

1. The Font Color
2. The Background Color
3. The Font Itself

I will quit bugging you about my own preferences.

Thanks for listening.

**Comment by jdanielmourao** [comment]
> Ah. It's subtly perhaps then is why have yet to discern a difference with `inline code` produced by any currently available options. Having said that, the changes, of course, with full code blocks is very obvious.
> 
> My individual desire would be to be able to change the following with `inline code`, in order of priority:
> 
>     1. The Font Color
> 
>     2. The Background Color
> 
>     3. The Font Itself
> 
> 
> I will quit bugging you about my own preferences.
> 
> Thanks for listening.

The first 2 should be easy to implement. The 3rd one should actually already be possible — you just need to change `Appearance -> Monospace font`. That will affect inline code, code blocks, and frontmatter.
