### ISSUE TITLE
[BUG] The text under "heading indicator" and "disable lvl 5 and lvl 6 uppercase" is the same in Style Settings

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#149]
**Describe the bug**
The text under "heading indicator" and "disable lvl 5 and lvl 6 uppercase" is the same

**To Reproduce**
1. Go in "Style Settings's" setting
2. Go in "Typography"
3. Go in "Heading

**Expected behavior**
Having the text for uppercase heading changed

**Screenshots**
![Screenshot 2022-03-07 14 52 54](https://user-images.githubusercontent.com/79509045/157047684-bb7189a3-70d9-4885-a17c-c1ec648c08b1.png)

**Version [Desktop or Mobile]:**
Mobile and Desktop

**Editor**
Live Preview

**Additional context**
None

**Comment by jdanielmourao** [comment]
Thanks, this has been fixed. :)
