### ISSUE TITLE
[BUG] System window does not scale with app window

### ISSUE THREAD

**Issue by Relkion** [jdanielmourao/obsidian-sanctum#151]
<img width="816" alt="Screen Shot 2022-03-16 at 7 47 48 PM" src="https://user-images.githubusercontent.com/101229519/158727096-25ae188c-94ec-400d-aac4-a5db5c834730.png">

**Comment by jdanielmourao** [comment]
Hi! There are currently Style Settings options for customizing menu window sizes. I'd advise checking if any of those have been changed. I'm planning on making it adapt more smoothly, but it may take a couple of weeks before I get to it.
