### ISSUE TITLE
[IDEA/REQUEST]: Option to disable tag styling

### ISSUE THREAD

**Issue by Relkion** [jdanielmourao/obsidian-sanctum#152]
**Is your feature request related to a problem? Please describe.**

Not able to color code tags with CSS snippet.

**Describe the solution you'd like**

Option in style settings to disable the styling to tags.

**Describe alternatives you've considered**

Living with colorless tags. I am very close to code illiterate, so fixing this on my own is somewhat beyond me.

**Additional context**

None.

**Comment by jdanielmourao** [comment]
Hi! You can make your custom tag colours using the following snippet:

```css
.markdown-preview-view a.tag[href='#custom1'],
.markdown-source-view span.cm-hashtag.cm-tag-custom1 {
	background-color: var(--color-primary-0);
}```

**Comment by jdanielmourao** [comment]
Update: I'll be looking into ways of easily setting this up via style settings.

**Comment by jdanielmourao** [comment]
So I've taken a look at it, and it doesn't look like there's anything I can do about tags, unless I make preset tags, which would defeat the purpose of people being able to make their own. Having said that, I'll be closing this issue.
