### ISSUE TITLE
[BUG] New admotions and double quote

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#154]
**Describe the bug**
The double-quote are weirdly made when using the new admonition block

**To Reproduce**
1. do : 
```
> [!note]
Some text
>> [!note]
Some other text
```

**Expected behavior**
Maybe a new way for the double quote, or detecting the admonitions?

**Screenshots**
![image](https://user-images.githubusercontent.com/79509045/160458821-092e286f-5a8b-4203-8db8-6ba636e204ba.png)
![image](https://user-images.githubusercontent.com/79509045/160458855-178cecb2-65a4-4dad-8b45-03f83ec283b9.png)

**Version [Desktop or Mobile]:**
Desktop (Linux and windows)

**Editor**
New CM6

**Additional context**
the padding/spacing seems off

**Comment by jdanielmourao** [comment]
This issue will be fixed with the next release!

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
