### ISSUE TITLE
[BUG] new live table

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#155]
**Describe the bug**
The new "live table preview does not respect the theme

**To Reproduce**
1. Do a table using Live Preview

**Expected behavior**
Made it so it uses the theme's table

**Screenshots**

**Version [Desktop or Mobile]:**
Desktop

**Editor**
New CM6 editor

**Additional context**
Here is the code for the table in live Preview, the Minimal theme has themed them if you want to look.
<div class="cm-embed-block markdown-rendered cm-table-widget show-indentation-guide el-table" tabindex="-1" data-tag-name="table" contenteditable="false"><table>

Tried to modify the CSS by adding 
.cm-embed-block markdown-rendered cm-table-widget show-indentation-guide el-table {
CSS code here
}
It didn't work for me.

**Comment by jdanielmourao** [comment]
This will be fixed next release!

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
