### ISSUE TITLE
[BUG] YAML codeblocks hidden throughout a note

### ISSUE THREAD

**Issue by mattdenner** [jdanielmourao/obsidian-sanctum#156]
**Describe the bug**
I have a note that has a YAML codeblock. This codeblock is a snippet of YAML related to what I'm writing about, not the frontmatter of the note itself. By default Sanctum appears to hide **any** content that is marked as YAML until you hover over, or tap, on a drop down icon. And if you are on a desktop machine the content is hidden if you move off the element.

A workaround is to use [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings) to enable showing YAML. However, this shows the frontmatter too.

**To Reproduce**
Create a note with the following content & view it in preview mode:
<pre>
---
tags: ["some tag"]
aliases: ["note about something in YAML"]
---
I want to remember the following YAML:
```yaml
foo:
  bar: value
```
</pre>

**Expected behavior**
I'd like to have the content of the codeblock visible.
I'd like to control whether frontmatter is visible, as you can now.

**Screenshots**
![Screenshot 2022-03-29 at 10 01 02](https://user-images.githubusercontent.com/140671/160575438-6d354a0b-6a4b-4f52-9eb2-5fa888d12069.png)

**Version [Desktop or Mobile]:**
v0.6.3 (both mobile & desktop)

**Comment by jdanielmourao** [comment]
This will be fixed with the next release!

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
