### ISSUE TITLE
[BUG]: Theme performance slowdown due to `backdrop-filter`

### ISSUE THREAD

**Issue by chrisgrieser** [jdanielmourao/obsidian-sanctum#158]
See the related issue in my theme's repo: https://github.com/chrisgrieser/shimmering-focus/issues/132

Removing `backdrop-filter` solved the issue. 🙂

**Comment by jdanielmourao** [comment]
Thanks. I already have a setting to disable that effect in modals, so I'll point people to that solution in the future. 👍🏻
