### ISSUE TITLE
[BUG] List markers do not show up correctly

### ISSUE THREAD

**Issue by angelineyeow** [jdanielmourao/obsidian-sanctum#159]
**Describe the bug**
Odd- and even-numbered list markers do not show up correctly.

**Expected behavior**
I am using the default settings for list markers, hence the odd-numbered levels should have the dash list marker and the even-numbered levels should have the small black square.

**Screenshots**
<img width="132" alt="image" src="https://user-images.githubusercontent.com/45735686/162627656-2fd58d78-0650-4e74-8936-5ab322b19265.png">

**Version [Desktop or Mobile]:**
Desktop

**Editor**
CM6 Editor

**Comment by jdanielmourao** [comment]
Hi! This was due to an obsidian update that changed the name of some classes of the lists, thus rendering the existing code obsolete. I've made a fix that will be in the next release.

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
