### ISSUE TITLE
[BUG] Hashtags either duplicated when in a heading or not shown completely

### ISSUE THREAD

**Issue by DeutscheGabanna** [jdanielmourao/obsidian-sanctum#161]
**Describe the bug**

Tags inside headings show hashtags twice. Tags inside normal text do not display hashtags at all.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
`## Heading 2 #tag
This is a normal paragraph #tag`

**Expected behavior**

One hashtag per tag.

**Screenshots**

![image](https://user-images.githubusercontent.com/59067099/163830916-03399d75-fe93-485c-82a5-2784f5fdaed1.png)

**Version [Desktop or Mobile]:**
win11

**Editor**

New.

**Additional context**

**Comment by DeutscheGabanna** [comment]
They appear to be working only in callouts, I noticed.
![image](https://user-images.githubusercontent.com/59067099/167274145-00f0ffbd-fa5d-4841-aaca-98b835235164.png)

**Comment by DeutscheGabanna** [comment]
`a.tag` when it's working in callouts:
![image](https://user-images.githubusercontent.com/59067099/167274153-345fc231-74ce-496f-9af1-196d764f0c2a.png)

`span...` when it's not working everywhere else:
![image](https://user-images.githubusercontent.com/59067099/167274157-d8b10a8e-c461-4437-94d0-80cf9f43ff05.png)

**Comment by jdanielmourao** [comment]
This issue will be resolved next release!

**Comment by DeutscheGabanna** [comment]
the man has returned!

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
