### ISSUE TITLE
[BUG] Close and Edit buttons missing in Sliding Panes (Andy's Mode)

### ISSUE THREAD

**Issue by AlexRimor** [jdanielmourao/obsidian-sanctum#162]
The close and edit buttons are missing when using Sliding panes. 
They are visible when using default and other themes. Images show in Sanctum vs other themes.
I'm using MS Windows 10. And the Obsidian Installer is up to date.

Using Sanctum:
![image](https://user-images.githubusercontent.com/81555748/164121273-b616842d-4ffa-4720-bbb8-b98a4d802679.png)

From another theme:
![Obsidian_BTKz0RX52I](https://user-images.githubusercontent.com/81555748/164121140-b52a5dc0-1e8d-4f63-81ce-af810a28d37a.png)

**Comment by jdanielmourao** [comment]
A fix for this bug will be issued with the next release! Be on the lookout for theme updates!

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
