### ISSUE TITLE
[BUG] Link styling doesn't work if inside a callout

### ISSUE THREAD

**Issue by DeutscheGabanna** [jdanielmourao/obsidian-sanctum#164]
**Describe the bug**

Link styling doesn't work if inside a callout

**Expected behavior**

Link styling should look like this:
![image](https://user-images.githubusercontent.com/59067099/167269127-cc53be71-77c5-4de5-ad68-a30fc831ed75.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/59067099/167269105-21df44b5-17ac-41e3-82aa-df9c9ccce181.png)
![image](https://user-images.githubusercontent.com/59067099/167269114-556116d4-4f57-4d69-8350-ab8b34f16d44.png)

**Version [Desktop or Mobile]:**
Desktop

**Editor**

CM6

**Additional context**

**Comment by DeutscheGabanna** [comment]
This snippet fixes the issue for me but probably is too "rough" for all users:
`a.internal-link {
  text-decoration: none;
  color: var(--text-accent);
  font-weight: 450;
  text-transform: uppercase;
  font-size: 0.8em;
  letter-spacing: 0.125em;
  border-radius: 4px;
}`

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
