### ISSUE TITLE
[BUG] Table header does not follow alignment.

### ISSUE THREAD

**Issue by nucspl** [jdanielmourao/obsidian-sanctum#165]
**Describe the bug**

In the title. Default theme nor Minimal theme doesn't face this.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Make a table in any note
2. On the separator line, use a colon on either side of the dash
Example table:
`Header 1|Header 2`
`-:|-:`
`Text|Text`
3. See error

**Expected behavior**

Something like this...
![image](https://user-images.githubusercontent.com/80261260/173190705-bdc4ff23-5a3c-4f41-b9dd-a1f9cecb4280.png)

**Screenshots**

The bug.
![image](https://user-images.githubusercontent.com/80261260/173190671-fde64f71-59d2-4eed-8807-ce3aa50006c2.png)

**Version [Desktop or Mobile]:** Desktop

**Editor**

CM6

**Additional context**

None

**Comment by jdanielmourao** [comment]
A fix for this issue will come with the next release.

**Comment by jdanielmourao** [comment]
This has been fixed. I recommend updating to the latest version of Sanctum! :)
