### ISSUE TITLE
[BUG] Highlighter incorrect color within callouts

### ISSUE THREAD

**Issue by amwnag** [jdanielmourao/obsidian-sanctum#166]
**Describe the bug**
Rather than appearing as yellow, highlights show up as a dark green.

**Markdown**
```
> [!note]
> ==123==

==123==
```

**Expected behavior**

Highlighter color would be consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/86573349/173933131-a84df843-ac5f-4ef8-8ab6-b1068ca575c0.png)

**Version [Desktop or Mobile]:**
Desktop

**Editor**

New CM6 editor

**Comment by jdanielmourao** [comment]
It has been fixed. I recommend updating to the latest version of Sanctum! :)
