### ISSUE TITLE
[BUG] Checkbox styling fails for task lists contained in an embedded markdown document

### ISSUE THREAD

**Issue by rp-preger** [jdanielmourao/obsidian-sanctum#167]
**Describe the bug**
Normally, Sanctum displays circular checkbox icons for task lists.  But when you embed one md document in another using `![[embed.md]]` syntax, checkbox icons display as either circles or **squares** depending on whether the Editor is in View or Edit mode.

**To Reproduce**
1. Create a md file`bar.md` containing a task list `- [ ] an item` 
2. Create a 2nd md file `foo.md` that embeds the first with `![[bar.md]]`
3. Open `foo.md` in Editor.
4. Alternate between Edit and View modes in Editor to observe different checkbox styles.

**Expected behavior**
Checkboxes should always display according to Sanctum CSS.

**Screenshots**
`June File List.md` embeds `Daily 2022-06-19 Sun.md`. 

Editor in View mode:
![Editor in View mode](https://user-images.githubusercontent.com/31174643/174688702-1a8fd887-f351-403f-827c-382f72d9dcd7.png)

Editor in Edit mode:
![Editor in Edit mode](https://user-images.githubusercontent.com/31174643/174688713-96e9a282-7f9a-460e-9664-95c6961e81e1.png)

**Version [Desktop or Mobile]:** Both

**Editor**
Latest Editor

**Additional context**
None

**Comment by glasszay** [comment]
I have a similar problem with callout blocks, It only seems to occur when in edit view:

![image](https://user-images.githubusercontent.com/76571965/175888559-305cb225-e1c4-401e-b529-bc385363715a.png)

**Comment by jdanielmourao** [comment]
This is currently partly resolved. I have still to fix it for callouts, but will work on it next.
