### ISSUE TITLE
[BUG] List indent when soft-break a line is wrong 

### ISSUE THREAD

**Issue by ironhak** [jdanielmourao/obsidian-sanctum#168]
**Describe the bug**

As you can see, when I try to soft-break a line, then the second line will not be aligned with the rest of the text. 
![Screenshot 2022-06-28 at 09 57 26](https://user-images.githubusercontent.com/62611612/176125500-a1f0ffd5-ea24-410b-afbe-626b10c15c35.png)

Plus, the first non-visible character of the line will have a wrong font size, here's the size of the first non visible character:
![Screenshot 2022-06-28 at 09 50 34](https://user-images.githubusercontent.com/62611612/176125856-dcd5ffe2-f37b-4916-a97d-39fe512e058f.png)
Here's the correct size of the editor:
![Screenshot 2022-06-28 at 09 51 24](https://user-images.githubusercontent.com/62611612/176126023-c15378d0-bc5b-49f3-9a05-5a2fc5698fd9.png)

**Editor**

I'm using live-preview mode. On preview mode this issue will not be present.

**Comment by jdanielmourao** [comment]
Hi there! Are you still experiencing this issue? I don't seem to be able to replicate it.

**Comment by nucspl** [comment]
It's still present in Sanctum 0.15.9, it seems to misalign conversely when using source mode too.

**Reading**, no issue on both:
![image](https://user-images.githubusercontent.com/80261260/185725905-f6411d31-1687-4aa9-a83c-e00ef5276344.png)

**Live preview**, has the issue prescribed above:
![image](https://user-images.githubusercontent.com/80261260/185725725-f2aa4931-5108-4721-89dd-fc41b041ac6e.png)

**Source mode**, soft-break is aligned, word wrap is not:
![image](https://user-images.githubusercontent.com/80261260/185725863-58b81cbc-393c-4394-9da8-68cbfabe3c19.png)

**Comment by jdanielmourao** [comment]
This shouldn't be an issue in the latest release of Sanctum. Note that this release is currently only available to Obsidian Insiders who have access to Obsidian 0.16.x (which is in testing phase). Hopefully that Obsidian version will release in the coming weeks (there's no release date, but I have the feeling it's not going to take long).
