### ISSUE TITLE
Issue with styling citation "[@cite]" and  ":" character

### ISSUE THREAD

**Issue by danieltomasz** [jdanielmourao/obsidian-sanctum#17]
Great theme!

Sometimes I have a small problem with styling of citations:
I have specific fragment:
```
- From [@botcharova2014ModellingAnalysisAmplitude]:
	- Assesing the presence of LRTC in the amplitude envelope of EEG and EMG
````
It will render like that:
![image](https://user-images.githubusercontent.com/7980381/138304334-264f09fe-4c39-4d06-afb9-6b2448b75749.png)
When I put the space after the citation and before ":"
```
- From [@botcharova2014ModellingAnalysisAmplitude]  :
	- Assesing the presence of LRTC in the amplitude envelope of EEG and EMG
```
Its renders normally
![image](https://user-images.githubusercontent.com/7980381/138304170-b156e873-46d0-4b8d-894b-7cc719e982b7.png)

**Comment by jdanielmourao** [comment]
Thanks for spotting it! Once you add the colon, Obsidian starts treating it as a footnote, hence the change in formatting. I'll go ahead and change that.

**Comment by danieltomasz** [comment]
Maybe it can be solved on the Obsidian level, thanks for the effort and for making such great theme!
