### ISSUE TITLE
Style Settings does not include Highlight Colors

### ISSUE THREAD

**Issue by ecstatic-shark** [jdanielmourao/obsidian-sanctum#171]
Highlight Colors is listed as a customizable option in Style Settings on the Wiki [here](https://github.com/jdanielmourao/obsidian-sanctum/wiki/Style-Settings-Options). It doesn't show up in any of the options/sections/submenus within the Style Settings options. It looks like everything else shown on the wiki page is in Style Settings.

**Comment by jdanielmourao** [comment]
Next update should include highlight colour options again, with some presets.
