### ISSUE TITLE
File explorer bug, doesn't load files

### ISSUE THREAD

**Issue by almita** [jdanielmourao/obsidian-sanctum#172]
When I scroll down on the file explorer files don't load immediately, I saw there was a closed issue about this on MacOS, this is in Windows...

![Obsidian_UErasF12Tp](https://user-images.githubusercontent.com/47606562/179381418-66601385-e97c-48f2-9ec0-231c77c002f4.gif)

**Comment by jdanielmourao** [comment]
Hi! Have you tried enabling Restricted Mode (`Settings ➡️ Options ➡️ Community Plugins`), to see if it affects it? I'd also recommend deleting the theme and redownloading, in case it makes a difference. 
I haven't been able to reproduce this on Windows so far.

**Comment by jdanielmourao** [comment]
Hello again! Have you noticed any changes?

**Comment by almita** [comment]
Hi! Sorry for not responding sooner, I haven't had the problem since then. I updated the theme not long ago and it has been working perfectly. Thank you!
