### ISSUE TITLE
Bug?: File Info Panel font size

### ISSUE THREAD

**Issue by oldjove** [jdanielmourao/obsidian-sanctum#173]
### Bug Description

I use the File Info Panel plugin. Up until 0.15.8, the font size of that panel was nice and small. Now the font size has increased, which means that the panel takes up more screen real estate. I've also noticed that, in contrast to Minimal, adjusting the font size slider has no effect on the font size in the File Info Panel. Not sure if that's relevant.

### To Reproduce

Open File Info Panel

### Expected behavior

Earlier, smaller font, to be retained in display.

### Relevant Screenshot(s)

In Sanctum:

![image](https://user-images.githubusercontent.com/47560940/180987583-299e76e0-4be7-4a90-b025-3444cbd9884f.png)

In Minimal:

![image](https://user-images.githubusercontent.com/47560940/180987847-eea9a4dd-ff1d-492b-8005-52a87a688ee9.png)

### Obsidian Version

0.15.8

### Installer Version

0.14.6

### Font Size

15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Reading View (Preview)
- [X] Editing View - Source Mode
- [X] Editing View - Live Preview

### Which operating system?

- [X] Windows
- [ ] macOS
- [ ] Linus
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

**Comment by jdanielmourao** [comment]
If you update now, it should be fixed!

**Comment by oldjove** [comment]
Thanks for the quick response!
