### ISSUE TITLE
[Bug] Adding link in task creates extra spaces

### ISSUE THREAD

**Issue by oldjove** [jdanielmourao/obsidian-sanctum#174]
### Bug Description

If I try to create a new link while in a task by typing two square bracket, extra spaces are opened up both within the brackets outside the brackets. The extra spaces don't show up in reading view, only in source mode and live preview. This only seems to happen in top-level tasks, not in subtasks.

### To Reproduce

Create a wikilink while inside a task.

### Expected behavior

Wikilink to be created as normal.

### Relevant Screenshot(s)

![image](https://user-images.githubusercontent.com/47560940/180990830-8b3dc06b-c5a6-4e2c-a4cb-fc5cd02fbbff.png)

### Obsidian Version

0.15.8

### Installer Version

0.15.8

### Font Size

15

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Reading View (Preview)
- [X] Editing View - Source Mode
- [X] Editing View - Live Preview

### Which operating system?

- [X] Windows
- [ ] macOS
- [ ] Linus
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

**Comment by jdanielmourao** [comment]
If you update now, the issue should be fixed.

**Comment by oldjove** [comment]
Marvellous. Thanks!
