### ISSUE TITLE
Bug: iPad, find takes up whole screen, can't be dismissed

### ISSUE THREAD

**Issue by ljodell** [jdanielmourao/obsidian-sanctum#176]
### Bug Description

on ipad, using cmd + F to bring up the search brings up a fullscreen search that cannot be dismissed and the whole file needs to be closed to get out of the window. clicking on other windows still has the search bar covering everything.

![IMG_1447](https://user-images.githubusercontent.com/45466708/182929478-274a84d6-d2cb-4e27-83ba-0fc307050fb4.jpeg)
 

### To Reproduce

anytime search is used within any .md document

### Expected behavior

i expected the find to appear at the bottom as it does in the default theme/other themes

### Relevant Screenshot(s)

![IMG_1447](https://user-images.githubusercontent.com/45466708/182929806-327f4199-e9ed-473d-80d3-591e06263692.jpeg)
![IMG_1448](https://user-images.githubusercontent.com/45466708/182929823-1563902b-50fa-4d6d-aed7-85d4a76d9af5.jpeg)

### Obsidian Version

0.15.6

### Installer Version

1.3.0(63)

### Font Size

16

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Reading View (Preview)
- [X] Editing View - Source Mode
- [X] Editing View - Live Preview

### Which operating system?

- [ ] Windows
- [ ] macOS
- [ ] Linus
- [ ] Android
- [X] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

**Comment by jdanielmourao** [comment]
Hi! The windows appearing at the top is intended. However, it's not supposed to hide the close button. I'll have a look at it.

**Comment by jdanielmourao** [comment]
This should have been solved with the newest update. I can open this again should the issue return.
