### ISSUE TITLE
Bug: the width of the "Settings" menu except for some problems

### ISSUE THREAD

**Issue by ouatis** [jdanielmourao/obsidian-sanctum#178]
### Bug Description

I don't know why, but after updating to version 0.15.9, my "Settings" menu screen became unusually narrow. I can't resize it either.

I thought at first that it was because I was using Simplified Chinese, but after switching to the English version, I found that I still had the problem. But switching back to the default theme, I don't have this problem anymore, that's for sure.

Maybe it has something to do with this latest update note: Settings menu’s width scales with app window (no more minimum size);

I hope you can help to solve this problem, thank you very much.

### To Reproduce

1.  Go to Setting menu.
2. "Settings" menu screen became unusually narrow.

### Expected behavior

I would like it to display the width normally.

### Relevant Screenshot(s)

![screenshot-20220810-131801](https://user-images.githubusercontent.com/53555223/183822064-3cf7a1cf-cb11-4b66-a4b4-b96815ea4099.png)
![screenshot-20220810-131823](https://user-images.githubusercontent.com/53555223/183822075-d25e2387-5484-41b8-b4b2-49bdba0a0d2a.png)
![screenshot-20220810-131910](https://user-images.githubusercontent.com/53555223/183822084-418dceab-4bf6-48eb-9337-29b60f184947.png)
![screenshot-20220810-131847](https://user-images.githubusercontent.com/53555223/183822087-71305f69-33db-48ad-beec-e44940536cd7.png)

### Obsidian Version

0.15.9

### Installer Version

0.15.8

### Font Size

10

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Reading View (Preview)
- [X] Editing View - Source Mode
- [X] Editing View - Live Preview

### Which operating system?

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

### Additional Context

I just started using Obsidian. and I don't know how to program at all. I hope my not-so-professional description will help you solve the problem.

**Comment by jdanielmourao** [comment]
Hello! You should still be able to customize the width of the modals using Style Settings! You'll just need to go to Elements -> Modals.

**Comment by ouatis** [comment]
Oh I get it. I didn't use this plugin before, but now I installed it. Problem solved! Thank you.
