### ISSUE TITLE
Feature Request: Monospace tables

### ISSUE THREAD

**Issue by NerdKnight66** [jdanielmourao/obsidian-sanctum#182]
### Feature Requested

Make the font monospace in tables

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by jdanielmourao** [comment]
Even though this is older, consider following the issue here: https://github.com/jdanielmourao/obsidian-sanctum/issues/184 as that's more complete.
