### ISSUE TITLE
Bug: Plugin Supercharged Links does not work in Live Preview mode

### ISSUE THREAD

**Issue by Trikzon** [jdanielmourao/obsidian-sanctum#183]
### Bug Description

I am using the plugin [Supercharged Links](https://github.com/mdelobelle/obsidian_supercharged_links) to color-code my links based on what tag they have. This works in the rendered reading mode, but not in live preview mode. The default Obsidian theme works fine with it.

### To Reproduce

1. Install Sanctum theme
1. Install Supercharged Links
2. Set a new selector to a tag in Supercharged Links' settings with "Style link text" enabled.
3. Install Style Settings plugin
4. Set selector's color in Style Settings' settings.
5. Create a note with the tag
6. Link to the note and notice that in Live Preview mode it doesn't have the correct color.

### Expected behavior

I would expect the coloring by the Supercharged Links plugin to work in Live Preview mode.

### Relevant Screenshot(s)

With Sanctum in Reading Mode:
![image](https://user-images.githubusercontent.com/29845000/185808121-f1a0a029-92ee-479b-9b23-5dbe89fd1a97.png)

With Sanctum in Live Preview Mode:
![image](https://user-images.githubusercontent.com/29845000/185808132-3d44278b-eb71-45a0-9809-a2f020ef2728.png)

With Obsidian's default theme in Reading Mode:
![image](https://user-images.githubusercontent.com/29845000/185808148-6088b15e-dd51-4ad7-a4b7-1bb1ade6c89f.png)

With Obsidian's default theme in Live Preview Mode:
![image](https://user-images.githubusercontent.com/29845000/185808158-5c542eb9-69ca-402f-abbb-5c1769138fd2.png)

### Obsidian Version

0.15.9

### Installer Version

0.15.9

### Font Size

16

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Reading View (Preview)
- [ ] Editing View - Source Mode
- [X] Editing View - Live Preview

### Which operating system?

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

**Comment by jdanielmourao** [comment]
Hi, sorry for the delayed response! That may be because of the heavy styling of links in Sanctum's version for Obsidian 0.15.9, which may overwrite some of Supercharged Links' formatting. That should not be an issue in the next version which I'm developing for Obsidian 0.16 (currently in insider testing).

**Comment by Trikzon** [comment]
Just tested out 0.16 and it works! Awesome!

P.S. I notice that the warm off-white light mode theme doesn't exist anymore? That or I can't find the setting for it. Are there plans on bringing that back?

**Comment by jdanielmourao** [comment]
> Just tested out 0.16 and it works! Awesome!
> 
> P.S. I notice that the warm off-white light mode theme doesn't exist anymore in the 0.16 version? That or I can't find the setting for it. Are there plans on bringing that back?

The theme's color palette has been revamped to improve contrast ratios further, and uses more natural tones. Atm, there are new "contrast modes" I've created, but no color schemes as of yet. My plan is to add color schemes or even the possibility for custom ones, but only after I take care of other more pressing features/formatting.

**Comment by Trikzon** [comment]
Awesome, I look forward to it. Thanks for the amazing theme!
