### ISSUE TITLE
Advanced tables no longer pretty

### ISSUE THREAD

**Issue by pdworkman** [jdanielmourao/obsidian-sanctum#184]
Under Default theme, Advanced tables plugin makes my tables look like this while I am editing:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/91858203/185818716-c647721c-24b4-46e5-85fa-847710b14cd5.png">

With the latest Sanctum release, my tables look like this:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/91858203/185818801-c461a2e3-dbb8-4fb8-b261-a8db75e0848d.png">

I can still edit them, of course, but I have to count my columns and everything isn't automatically lined up and easy to read.

**Comment by jdanielmourao** [comment]
This issue will be resolved once the next version of Sanctum comes out (whenever Obsidian 0.16 comes out).

**Comment by pdworkman** [comment]
Awesome. In the meantime I know that if I have a table that is difficult to visualize and edit, I can switch to default theme and then back again when I am done.
