### ISSUE TITLE
Bug: settings panel is horizontally compressed

### ISSUE THREAD

**Issue by dsteinbock** [jdanielmourao/obsidian-sanctum#185]
### Bug Description

Updated today and the Obsidian Settings screen became super narrow. I see there was a new change to the Settings stylings but my window is very wide and the Settings are still much too narrow, disrupting the contents. See screenshot.

### To Reproduce

Install newest Sanctum in unmodified Obsidian.

### Expected behavior

Settings screen should be readable.

### Relevant Screenshot(s)

<img width="1590" alt="Screen Shot 2022-08-23 at 4 35 23 PM" src="https://user-images.githubusercontent.com/4734875/186284427-e8f98de4-b4fb-4169-91f2-74762b454095.png">

### Obsidian Version

0.15.9

### Installer Version

0.15.9

### Font Size

10

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Reading View (Preview)
- [ ] Editing View - Source Mode
- [ ] Editing View - Live Preview

### Which operating system?

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

**Comment by jdanielmourao** [comment]
Hi! There should be a style settings option to adjust the settings menu width to your preference. :)
