### ISSUE TITLE
Bug: Snippet no longer works

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#186]
### Bug Description

I have a snippet for capitalising inner links:

This still works on updated themes, but no longer on Sanctum - my favourite.

I'm sure you have much work now re-write this theme's CSS for 0.16.  But if you could check on this, it would be much appreciated. 

### To Reproduce

Use Sanctum with snippet:

span.cm-hmd-internal-link, a.internal-link {
 text-transform: uppercase; 
}

### Expected behavior

I expect to see capitals [[CAPITALS]]

### Relevant Screenshot(s)

Latest Sanctum
![image](https://user-images.githubusercontent.com/73867063/187598814-35eab9fd-602e-48bb-9688-27c6bb052892.png)

Default theme:
![image](https://user-images.githubusercontent.com/73867063/187598857-5657c86f-1cc2-4961-a75b-c0c3ebeca7b0.png)

### Obsidian Version

0.16

### Installer Version

0.15.9

### Font Size

14

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [X] Reading View (Preview)
- [X] Editing View - Source Mode
- [ ] Editing View - Live Preview

### Which operating system?

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.

### Additional Context

No additional context

**Comment by jdanielmourao** [comment]
Hi! Sanctum's version for 0.15.9 should have a built-in link formatting for caps, which is can be toggled off in Style Settings. Have you checked if that option in toggled? That may be overwriting your snippet.

**Comment by kmaustral** [comment]
I couldn't find a setting for that. Is it in Internal Links? I get
underline or italics.

**Comment by jdanielmourao** [comment]
Oh, my bad, I saw the installer version and confused it with the Obsidian version! There should be an internal link text transform Style Settings option in the most recent version (which I have just now released). It might be immediate, or you might have to wait a few minutes for Github's cache to kick in, and the community themes store to update.

**Comment by kmaustral** [comment]
Thanks. I updated the theme, but now there is no section for Sanctum in the
Style Settings.
