### ISSUE TITLE
[BUG]: Right Sidebar toggles disappears on click

### ISSUE THREAD

**Issue by chrisgrieser** [jdanielmourao/obsidian-sanctum#187]
![Kapture 2022-08-31 at 14 05 10](https://user-images.githubusercontent.com/73286100/187674468-2e3e4e8b-f30d-4ddd-978e-12c7c5dbea1b.gif)

ngl, I have implemented something similar in Madness Mode ;)

**Comment by jdanielmourao** [comment]
As that's a obsidian bug, I'll close this. ;)
