### ISSUE TITLE
Feature Request: Mark dependencies for individual scss files

### ISSUE THREAD

**Issue by NomarCub** [jdanielmourao/obsidian-sanctum#190]
### Feature Requested

I only want to use checkboxes for my own purposes, but it took me a while to whittle down what is needed for them to work. This repo used to have snippets, which I used up until the latest Obsidian update. Maintaining snippets might be a hassle, but marking dependencies for scss files seems like a good middle ground to me. That way people who just want a small feature can still pick and choose.
I'd imagine keeping track of dependencies for its own sake has other potential benefits for continued development.

In my use-case, just adding `@use "../variables/colors";` and `@use "../components/checkbox";` to the top of the file makes it so I can execute `sass src/scss/features/custom-checkboxes.scss snippet.css` and get only what I want.

### Relevance

- [X] The feature would be useful to more users than just me.

### Style Settings

- [X] I have checked that the feature is not already available via the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).

**Comment by jdanielmourao** [comment]
Hi! I'm not sure I fully understand what you mean by "marking dependencies". Since the theme's been broken down into small modules, it's relatively easy to find certain features and convert the code into css, like you explained. Granted not everyone has the know-how of how to do that.
In case this answers your request, I'm planning on adding proper documentation to the theme (currently exploring Github Pages as an option), where I could add a link to the specific scss modules where each feature is located. I could have a page to explain how to convert said modules into css for use as a snippet (I've written an article over at Obsidian Hub about scss, so it'd only be a matter of linking to it as a resource). Do you think that's suffice?

**Comment by NomarCub** [comment]
By marking dependencies, I simply mean having `@use` statements in each file, so that they can be assembled from places other than the index. I came for checkboxes, and needed trial and error to see what else I need for them to work. With some the `@use` statements already present and some instruction about SASS, no one would need to guess.

More documentation would make this request less relevant for sure. And I would add to that, that good code documents itself. Having `@use` statements at the top of each file would be a developer and tooling-friendly way of documenting which snippet requires which other one. Having to read the docs is not a lot to ask from someone, but it's one more step removed from true modularity, and not good enough for good tooling. Ideally, I'd like to be able to execute `sass` on any module and get a result that works on its own.
I think this would make documenting easier for you too. Instead of explaining each module's dependencies at length in text, you could just tell people to execute `sass` (or your equivalent command) on any module and all the dependencies would be handled by SASS. Having the dependency explanation in a different place than the code also means they have to be maintained together, which takes more effort and is more error-prone.

On an somewhat unrelated note: does `custom-checkboxes.scss` even require `checkbox.scss`? It seemed to work fine without it at a glance. Does it require anything else besides `colors.scss`?

And one last thing: thanks for the article, and the theme! The article was a good starting point for organizing my existing CSS, and I loved the theme's features for a long while.

**Comment by jdanielmourao** [comment]
`custom-checkboxes.scss` should only need `colors.scss`, yeah. It specifically targets "special" checkbox syntax, so it doesn't affect regular checkbox code, which is formatted in `checkbox.scss`.

**Comment by jdanielmourao** [comment]
Alright, I just went through every scss module, and they should all now work as individual snippets. If you happen to find an error on my part, be sure to report it as a bug. :)

**Comment by jdanielmourao** [comment]
Also, turns out I had to comment out the dependencies on each scss module, because otherwise it won't let me build the theme file (which I had forgotten about). In any case, they'll still be present in the file, so it'll be easy to know what that file needs in order to correctly build a full snippet.

**Comment by NomarCub** [comment]
Isn't it just a problem with relative paths?
I put `@use '../variables/colors';` at the beginning of custom-checkboxes uncommented, and `npm run build` ran fine and produced an identical output.

**Comment by jdanielmourao** [comment]
It is, I just didn't have time to fix it today. 😅I'll troubleshoot it and update every file tomorrow

**Comment by NomarCub** [comment]
Hey there! I think you missed updating this.

**Comment by jdanielmourao** [comment]
Hi! I took a few days off to recharge and take care of some things irl. I'll take a look at it soon.

**Comment by NomarCub** [comment]
I found a typo in the file, I guess I'll just post it here: https://github.com/jdanielmourao/obsidian-sanctum/blob/34c7803c890645c6adba53f93360f64c14cca9d0/src/scss/features/custom-checkboxes.scss#L424

**Comment by NomarCub** [comment]
Hi!
This is still not resolved. Please at least reopen the issue, if you don't have the time for it.
