### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by DutchPete** [jdanielmourao/obsidian-sanctum#2]
In version 0.2 On hover it covers the entire vertical canal, as described in my personal message.

And the scroll bar in the file explorer is gone.

**Comment by DutchPete** [comment]
Why have you closed this issue? It has not been resolved.

**Comment by jdanielmourao** [comment]
Issue is confirmed to be resolved by OP, via dm.

**Comment by DutchPete** [comment]
I confirm resolution.
