### ISSUE TITLE
Mixed Case Font when Creating a New Note

### ISSUE THREAD

**Issue by rypgis** [jdanielmourao/obsidian-sanctum#210]
## To reproduce
Create a new note using the button in the left file navigation sidebar:
![image](https://user-images.githubusercontent.com/120662318/207897224-d347cdaa-c5cb-44d8-aca5-a427a1de3062.png)

The entered font has a mixed-case formatting:
![image](https://user-images.githubusercontent.com/120662318/207897348-eea0288e-9f69-4727-b9b5-cb3540e9e82f.png)

## Expected Behavior
The text in the input box should have the same formatting (case) as the final heading at the top of the note.

## Details
Obsidian version: v1.0.3
Installer version: v1.0.3
Operating System: Windows 10

**Comment by pad-mac** [comment]
![grafik](https://user-images.githubusercontent.com/10145613/208248349-770bc78b-955e-45db-8957-0104cc598487.png)

It appears that the Arial font is rendered like this when the Sanctum theme is applied. When i switch to default theme Arial is rendered normally in this picker. For me the issue occurs with a lot of interfaces created by plugins, so i assume a lot of them use Arial in their custom css. (Although it seems odd why they should replace the global font settings.) 

I don't know a lot of css, but searching the Sanctum code for some terms i didn't find any reason why the Arial font should be explicitly replaced. Maybe someone more knowledgable can help. I can provide a lot more reproductions in several different contexts.

**Comment by pad-mac** [comment]
Okay i can update that this doesn't seem to appear on mobile with the same theme settings, which confuses me even more.

Here is a test with the rich links plugin:

![grafik](https://user-images.githubusercontent.com/10145613/208251829-58c85d53-3bc2-4bcf-94db-42f3140d1e8d.png)

![grafik](https://user-images.githubusercontent.com/10145613/208251872-f3e6ccb3-c918-4249-86ed-666dac43785c.png)

**Comment by nathonius** [comment]
I've seen this intermittently. It comes and goes; I'm not sure what causes it and usually a restart of obsidian seems to fix it.

**Comment by rypgis** [comment]
It looks like this may have been fixed in the latest update of Obsidian (v1.3.4).
