### ISSUE TITLE
Space between lines in the command menu when the title is extending more than one line

### ISSUE THREAD

**Issue by danieltomasz** [jdanielmourao/obsidian-sanctum#22]
I have a question about the space - it was the a conscious design decision or the oversight?

![image](https://user-images.githubusercontent.com/7980381/138974292-58095873-49bc-4737-bdc3-cf3b603acbcf.png)

The obsidian native theme has a title more space  between lines  when the command line is extending in 2 lines

![image](https://user-images.githubusercontent.com/7980381/138974215-2f3b7423-f089-41e0-b0a5-6b1eb48bf588.png)
It has a bit more "air" in my opinion
This issue may be closed this is a decision :) 

Great idea about using color accent for plugin name!

**Comment by jdanielmourao** [comment]
Please confirm if the issue is resolved with the new update! 😉

**Comment by danieltomasz** [comment]
It's solved!
