### ISSUE TITLE
Settings icon on Ipad is wrong positioned (partially hidden)

### ISSUE THREAD

**Issue by danieltomasz** [jdanielmourao/obsidian-sanctum#25]
On iPad (tablet) mobile, the settings icon is partially hidden, the icon for phone is ok
![image](https://user-images.githubusercontent.com/7980381/139200065-555823ed-c79e-44bd-a126-066ffb89b4f7.png)

**Comment by jdanielmourao** [comment]
Please confirm if the issue is resolved with the new update! 😉

**Comment by danieltomasz** [comment]
Now it is ideal. Closing!
