### ISSUE TITLE
[IDEA/REQUEST] Tables Ignore Readable Line Width

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#26]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I go to look at a dataview table and everything is scrunched because of readable line width, because I have to go turn _off_ readable line width, which doesn't have a toggle, plus sometimes my dataview tables are in files that have text that I would like to still be a readable line width. 

**Describe the solution you'd like**

It would be cool if Sanctum automatically made tables go beyond the max width. 

**Describe alternatives you've considered**

I've considered asking for a hotkey for this, but for reasons stated above this is only a partial solution. 

**Additional context**

My dataview tables usually look something like this:

![image](https://user-images.githubusercontent.com/75856959/139594728-aa042ee6-a42a-4bfa-9127-9e8b1ff85bd4.png)

**Comment by jdanielmourao** [comment]
You mean like this? 😉 
<img width="1088" alt="Obsidian_2L5gCpBwmU" src="https://user-images.githubusercontent.com/91087143/139596442-34d369b9-ae75-4f15-b4f6-81f7553285e9.png">

**Comment by jdanielmourao** [comment]
The v0.2.6 update should add that feature!
