### ISSUE TITLE
[BUG] When there are too many Plugins installed, the settings does not scroll all the way

### ISSUE THREAD

**Issue by seanjun21** [jdanielmourao/obsidian-sanctum#27]
**Describe the bug**
When there are too many Plugins installed, the side panel on settings does not scroll all the way

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Go to 'Settings'
2. Scroll down all the way
3. Bottom plugins list get cut off

**Expected behavior**
You should see full list of plugins (screenshots below)

**Screenshots**
![image](https://user-images.githubusercontent.com/13973015/139775110-4374462d-e5df-4444-b02f-87c2bde07b62.png)
Error - you can see that the bottom plugins are not displaying

![image](https://user-images.githubusercontent.com/13973015/139775224-2b62312b-d4bd-432e-866d-96e82902aeeb.png)
Expected - Obsidian default theme displaying all the plugins

**Version [Desktop or Mobile]:**
- Desktop

**Additional context**

**Comment by jdanielmourao** [comment]
Hi! Could you try updating the theme? I've pushed a hotfix that will hopefully fix it.

**Comment by seanjun21** [comment]
Hi, so I just updated the theme, but it's still behaving the exact way.

**Comment by jdanielmourao** [comment]
I believe I may have found the issue with some help. Could you please try updating it one more time?

**Comment by seanjun21** [comment]
Unfortunately, still the same behavior.

**Comment by jdanielmourao** [comment]
It appears a part of the code I wanted to add got deleted right before saving and commiting. Here's to hoping that 3 time's the charm!

**Comment by seanjun21** [comment]
You are correct, 3rd time is the charm!
It's working now. Thanks for the hotfix!

![image](https://user-images.githubusercontent.com/13973015/140486969-8e95ae10-dbbe-4a64-9c22-0dbc362fd782.png)
