### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#29]
**Describe the bug**

Fantasy Calendar's "today" CSS class got overridden. 

**Expected behavior**

Here's what it looks like on a different theme: 
![image](https://user-images.githubusercontent.com/75856959/140573272-0e204a7a-e7ec-4559-afaa-d74838afa95b.png)

On Sanctum there's no indicator of what "today" is, just the "active" day. 

**Additional context**

This makes it hard for me to keep track of what day it is 😅

**Comment by jdanielmourao** [comment]
Gotta be honest, it was also something that was bothering me, but I didn't see it in default, so I thought it wasn't a feature 😅 It's been hotfixed, just update the theme and it should now show properly!

**Comment by eleanorkonik** [comment]
I only found out about it because I asked @javalent about it thinking it was a bug with fantasy calendar haha it's his screenshot.

Thanks for the hotfix! Will update as soon as I'm back at my desk :D
