### ISSUE TITLE
[BUG] CTRL+Scroll does not change font size in Edit mode

### ISSUE THREAD

**Issue by riddyrayes** [jdanielmourao/obsidian-sanctum#31]
**Describe the bug**
Not sure is this was intentional, but the CTRL+Scroll does not seem to change the font size in Edit mode.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Open notes side by side with preview and edit modes.
2. Press CTRL and Scroll
3. See error

OR

1. Go to Settings > Appearance
2. Move the Font size slider
3. See error

**Expected behavior**
The Editor font size should change like the preview view.

**Screenshots**
![Kp7qkpe7Yw](https://user-images.githubusercontent.com/76434115/140638455-67bd510d-977a-41d7-9283-bedb916be4a6.gif)

**Version [Desktop or Mobile]:**
Desktop

**Additional information**
Changing the variable unit in [this line](https://github.com/jdanielmourao/obsidian-sanctum/blob/7b5e587e878a9db87d83bfe5ed7ee6b56c24cc3d/obsidian.css?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1858) to "em" units changes the problem though.

**Comment by jdanielmourao** [comment]
This is actually an obsidian thing. I think you're only able to change preview font size for easier reading, but it keeps the editor font size the same. Even if I try setting it as something other than 16px, it will still display as 16px, so I'm assuming it's hardcoded into CodeMirror or something of the like. You can try not even setting a font size for Edit Mode, and you'll see that you still can't change it, which is the same case in default.
