### ISSUE TITLE
[BUG] Missing Publish Toggles

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#33]
**Describe the bug**
Sanctum seems to remove the toggle buttons for the Publish UI interface. They are important :(

**To Reproduce**
Attempt to Publish files

**Expected behavior**
I expect to be able to close top-level folders when trying to use Publish

**Screenshots**

Here's the default theme UI 
![image](https://user-images.githubusercontent.com/75856959/141125089-18b6d496-14de-4670-ad9b-5dd0acd8ceae.png)

Here it is with Sanctum

![image](https://user-images.githubusercontent.com/75856959/141125168-d99bd664-0e3f-4830-b0f3-c97a64f8fa46.png)

**Version [Desktop or Mobile]:**

Desktop

**Additional context**

Argentum had the same problem.

**Comment by jdanielmourao** [comment]
That's actually a completely unformatted page 😬 I don't pay for publish, hence why I haven't noticed it, although it's very weird that the buttons disappear... 🤔 I guess I'll have to either subscribe for a month or try another way of inspecting it all.

**Comment by eleanorkonik** [comment]
I'm happy to let you remote into my computer and inspect stuff on my screen if that would help, lol, but let me see if Silver has any way to emulate the interface for theme developers...

**Comment by jdanielmourao** [comment]
It appears I had forgotten to include the Publish Changes formatting in the update, so I pushed a small one. Should be good now!
