### ISSUE TITLE
Strange character capitalization[BUG]

### ISSUE THREAD

**Issue by ih8snow** [jdanielmourao/obsidian-sanctum#34]
Hi,
I installed the latest version of your theme and I noticed some strange headings / Reversed upper and lower case in the headings.

I don't see that when I use other themes
![sanctum1](https://user-images.githubusercontent.com/82544852/141273213-09b30f52-ef75-4ed7-bc67-15ee90eb2e68.jpg)
![sanctum2](https://user-images.githubusercontent.com/82544852/141273232-ff56014b-bb65-4eaf-9ea2-b43d0efd8bf7.jpg)
.

An< idea how I can fix that?

/ Jörn

**Comment by jdanielmourao** [comment]
Go to Style Settings -> Typography -> Fonts and click the arrow to go back to default.

**Comment by ih8snow** [comment]
Hi,
thanks for the info. Followed your advice, but no change in the "Explorer List" or in the Settings. (Did a reset of the font and all settinmgs in the "style settings")

The headers in the content are not touched by this.

When I check the ipad version of my vaul, using your theme, everything in the UI is ok.

Very strange...any other idea?

**Comment by ih8snow** [comment]
Update:
I deactivated all plugins, deactived core plugin fiel explorer, then restarted Obsidian.
Now I actived each plugin one by one...When I actived minimal themes settings...the probem started again.
Now same process plus uninstall of that plugin and the problem was solved.
Not sure how this is connected, but the problem is solved

**Comment by jdanielmourao** [comment]
Was Minimal Theme Settings enabled? If so, it might just be that this theme shares the same font variable name as Minimal, thus making the plugin affect it in unpredictable ways.

**Comment by ih8snow** [comment]
Yes, it was enabled. So really just the unusual combination of plugins .
Thanks for your feedback and help!
