### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by steelropes** [jdanielmourao/obsidian-sanctum#35]
Need to fix the padding on the quote block.

**To Reproduce**
Type:

">26. Then god said, “Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.” Genesis **1:26** "

**Expected behavior**
Line shouldnt cut through the quote block

THanks

**Comment by jdanielmourao** [comment]
Hi! This was a problem with having numbered list markers with a monospace font, making it way too wide for comfort. I have made a fix already, that will be out next update.

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been resolved with the latest update.

**Comment by steelropes** [comment]
![image](https://user-images.githubusercontent.com/38820879/143683196-4c855d9c-eb2b-445f-afa7-df12ffce64d5.png)
Still too close!

**Comment by steelropes** [comment]
Here is it customized with better space. And could even give more space to make it look nicer. The line is better than before from what i remember but still shouldnt be touching 
![image](https://user-images.githubusercontent.com/38820879/143683231-ef84d645-2ada-4396-89af-4b34f6a044b4.png)

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by steelropes** [comment]
> Please confirm if the issue has been fixed! :)

Nah, It's still the same distance. I changed it in the css to fix it, it's just a suggestion so you do the same and make the line farther away 

If youd like to recreate it its:

>26. Then god said, “Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.” Genesis 1:26

**Comment by jdanielmourao** [comment]
This is what I get with the current version fo the theme:
<img width="462" alt="Loom_XZMuVLyrCj" src="https://user-images.githubusercontent.com/91087143/144075946-477af83f-8626-4bce-ac80-125845187931.png">
Please make sure you don't have any snippets that might affect it turned on.

**Comment by steelropes** [comment]
Weird. Looks good on your screenshot but it's the same for me, even after
deleting the theme and adding it again.

**Comment by jdanielmourao** [comment]
Try disabling every snippet you have, as it can be overriding the theme.

**Comment by steelropes** [comment]
tried that

**Comment by steelropes** [comment]
Nope. I made a fresh vault as well. Maybe you didn't update it on the
public theme list

**Comment by jdanielmourao** [comment]
It came with the 0.4 update. Could you send me a screenshot of how it looks? If you could inspect it using developer tools (<kbd>Ctrl+Shift+I</kbd>/<kbd>⌘+Shift+I</kbd>), then (<kbd>Ctrl+Shift+C</kbd>/<kbd>⌘+Shift+C</kbd>) and click on the blockquote. It should show you on the right what's the css that is applying.
