### ISSUE TITLE
[IDEA/REQUEST] Table format 

### ISSUE THREAD

**Issue by anishvash** [jdanielmourao/obsidian-sanctum#38]
**Is your feature request related to a problem? Please describe.**
It will be great if there is an option available in style settings to display vertical lines between columns. Also good to have some options for more prominent lines (Like cell colors etc..). Similar to what is in the Blue Topaz theme. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It's a low-priority request.

**Comment by jdanielmourao** [comment]
It is already in the Roadmap ;) You can take a look at it [here](https://github.com/jdanielmourao/obsidian-sanctum/projects/1)
