### ISSUE TITLE
Google link preview icons

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#39]
Sanctum really rocks. Thank you.

Could I request link preview icons for Google links?

Including:
- https://mail.google.com
- https://drive.google.com
- https://docs.google.com

Other useful icons:
- https://wikipedia.org
- https://trello.com

The icons would help when these are used as hyperlinks, as a sign of where they lead. 

Thank you.

**Comment by jdanielmourao** [comment]
I will add it to the roadmap!
