### ISSUE TITLE
Feature request: progress bar when checking for plug-in updates

### ISSUE THREAD

**Issue by DutchPete** [jdanielmourao/obsidian-sanctum#4]
When one opens the Settings  > Community plug-ins, there is a button to check if any of the plug-ins have an update. When you click on the button, nothing happens for a bit until you see the pop-up in the top right corner telling you there are or there not any updates.

Waiting for that pop-up is a bit strange, as if nothing is happening. A kind of progress bar would be useful. The GIF shows what I mean; unfortunately I missed showing that final popup in, but you get the gist.

![progbar](https://user-images.githubusercontent.com/10794265/137448581-87b97fc7-ed88-4a44-bad9-37213dfdb41e.gif)

**Comment by jdanielmourao** [comment]
It's something that's been bugging me too tbh. I didn't really understand why it didn't show when I had left the exact space both the default theme and others leave for the loading bar. Apparently redefining the loading animation did the trick, and is working for me. It will be on the next release.
