### ISSUE TITLE
[BUG] - actually this explains it perfectly

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#40]
**Describe the bug**

In preview mode, [text] is larger font and different colour. 

![image](https://user-images.githubusercontent.com/73867063/141603158-bde15650-cc2a-42eb-bb66-323038a3d39e.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/73867063/141603190-2adc6634-0e4b-4aee-a1d2-a8612b7a31d6.png)

**Comment by jdanielmourao** [comment]
Hi! I've pushed a hotfix that should take care of that issue!
