### ISSUE TITLE
Highlight the pane in focus

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#42]
**Is your feature request related to a problem? Please describe.**

If more than one pane is open, you can't tell which one has the focus. This means an extra click to the pane before any task. 

**Describe the solution you'd like**

A format change to the title of the file when in focus, such as bold formatting or background colour change.

**Comment by jdanielmourao** [comment]
Thanks for the suggestion! I'll add it to the roadmap. :)
