### ISSUE TITLE
[IDEA/REQUEST] Remove the note icon from Starred notes

### ISSUE THREAD

**Issue by isle99** [jdanielmourao/obsidian-sanctum#43]
Add an option in Style Settings to remove the note icon from Starred notes similar to the option where you can remove the note icon from the File explorer.

**Comment by jdanielmourao** [comment]
Hi! In the next update, the "No File Icons" option will now also include the Starred Pane. I might even make it a separate option in the future, but I want to reorganize the whole Style Settings structure before adding more toggles, as the file is already quite extensive.
