### ISSUE TITLE
[BUG] Fold heading & indent

### ISSUE THREAD

**Issue by N1cl4s** [jdanielmourao/obsidian-sanctum#44]
Editor Setting > "Fold heading" & "Fold indent"
- Folding doesn't work unless you activate "Fold indent" as well
- Arrows that allow folding don't align with headings and indents (usually a few lines above the actual heading)

![image](https://user-images.githubusercontent.com/14186523/142201175-c65ce33a-5fc0-4706-8524-e09d0b59b466.png)

**Comment by jdanielmourao** [comment]
Hi! Unfortunately, I'm not able to replicate this issue. I'd advise you to, first, check your obsidian version, and then try to toggle off/disable any snippets and plugins you might have, which could be interfering.

**Comment by jdanielmourao** [comment]
Any luck with this issue? Has it fixed itself in the meantime?

**Comment by N1cl4s** [comment]
Nothing no. I went my way without the toggle.

**Comment by N1cl4s** [comment]
I am yes. Insider build.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

jdanielmourao ***@***.***> schrieb am Dienstag, 30. November 2021 um 16:28:

**Comment by jdanielmourao** [comment]
Are you still experiencing this issue?
