### ISSUE TITLE
[BUG] Horizontal rules sometimes incorrectly render in new WYSIWYG "live preview" beta

### ISSUE THREAD

**Issue by davecan** [jdanielmourao/obsidian-sanctum#45]
**Describe the bug**
When enabling the new "live preview" WYSIWYG mode, adding a horizontal rule `---` to a note sometimes causes the rendered line to appear on top of all content vertically centered on the pane and the full width of the pane. See images below.

This does not always happen in every note.

**To Reproduce**
Unclear. Enter `---` rule in a note. Some cases the behavior appears, others it does not.

**Expected behavior**
The rules appear in their expected position on the note.

**Screenshots**

With HR:

![image](https://user-images.githubusercontent.com/121290/142295922-f9bbba94-3151-48df-933e-a7bad5506d52.png)

Without HR:

![image](https://user-images.githubusercontent.com/121290/142295959-9c033260-faff-42a5-8274-8b44d74b3bc0.png)

**Version [Desktop or Mobile]:**  0.13.0 Desktop

**Comment by jdanielmourao** [comment]
I am aware of this issue, but I won't be working on it for the time being, since Live Preview is still in testing phase, and classes might change. Once it's out to the general public, and more stable, I'll issue a fix.

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)
