### ISSUE TITLE
[BUG] Smushed Blockquotes

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#46]
**Describe the bug**

Sanctum isn't recognizing my double-spaced blockquotes

**To Reproduce**
Make a blockquote with two paragraphs and put a blank line blockquote in between them. 
**Expected behavior**
The space should render in preview. It doesn't.
**Screenshots**
Here it is on base theme: 

![image](https://user-images.githubusercontent.com/75856959/142712857-a69d5ef2-63e1-4ada-a28c-f744f26e4be6.png)

Here it is on Sanctum:

![image](https://user-images.githubusercontent.com/75856959/142712859-34c9cf11-cd40-4444-a3ba-065a3cee7f57.png)

**Version [Desktop or Mobile]:**

Desktop

**Comment by jdanielmourao** [comment]
I've identified the issue. To fix it while I don't push out a fix (I'm restructuring everything). Simply use this snippet:
```
blockquote p {
    display: block;
 }
```
That should make it act like default

**Comment by jdanielmourao** [comment]
(clicked wrong button to submit comment, sorry 😅 )

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)
