### ISSUE TITLE
[Suggestion] Change code block colour for dark themes

### ISSUE THREAD

**Issue by KierenB** [jdanielmourao/obsidian-sanctum#47]
The current `--color-pink-500` code colour does not have enough contrast when dark mode is used. I changed it to `--color-orange-500` (which works well for me) but I'm not sure how to change it depending on whether dark or light mode is selected (as I suspect that `--color-orange-500` may be too light for light mode).

**Comment by jdanielmourao** [comment]
Hi! You can enable a high contrast background for dark mode code blocks in the style settings options. I will most tweak the palette in the coming future, though.
