### ISSUE TITLE
[IDEA/REQUEST] Suggestions for optimising default iA Writer fonts

### ISSUE THREAD

**Issue by huw** [jdanielmourao/obsidian-sanctum#48]
Heya—this one should be pretty quick but I didn't have the time to write up a PR. 3 things you could fix:

1. Right now you're loading the iA Writer fonts into the theme as `format('truetype')`, which is less space-efficient (about 3x). You can convert the variable fonts to `format('woff2-variations')` and save a good 100kb or so per font.
2. I don't think you're loading the fonts correctly to use the bold font weight (at least, I copied your code into a snippet on my iPad and it didn't work right). Since they're variable fonts, you need to explicitly set `format('woff2-variations')` (if you're fixing the first problem) at the end of each font and specify a range for the `font-weight` (ex. `font-weight: 400 700` for the iA Writer fonts). This will get bold to work while keeping space requirements low.
3. You're technically supposed to include the license for the iA fonts when you redistribute them ;)

It should be easy to fix; I went to the trouble of doing both of these steps myself for my personal theme, and [I uploaded them at this gist](https://gist.github.com/huw/0249b9201be026db2da9beb276e681ae). Probably a copy-paste job :)

**Comment by jdanielmourao** [comment]
Hi! First of all, thanks for the recommendations!
I should have paid closer attention to the font's license, and that's on me. I'll be including it in the next version, as well as encode it using the different format. I did used to have it with `woff2`, but when editing it several times and re-encoding, I must have used the ttf format without thinking too much of it.
As for the bold error, I believe it's a font issue, as reported in their repo. I've already tried the variable range for font-weight, but it did not fix the issue (it actually made other errors, for some reason). Thanks to the contribution of another member of the community, I now have a version of iA Quattro S with that bold issue fixed, which will be included in the next update.
Again, thanks for the feedback 😉

**Comment by huw** [comment]
Happy to help—I actually found your project through looking into the bold type issue 😅

I’m not _100%_ sure, but the bold issue you’re seeing with Quattro V could be down to different browsers’ support for variable fonts, or maybe just a couple problems with setting up the CSS. FWIW the code in my snippet is definitely working on the latest iPadOS & macOS, but it’s probably not the most robust support for wide OS & browser support ^_^

Cheers for taking a look and getting back so quickly!
