### ISSUE TITLE
aside <s class="aside-*"> displayed as strike-trough

### ISSUE THREAD

**Issue by shiMusa** [jdanielmourao/obsidian-sanctum#49]
**Describe the bug**
When using the aside html elements, e.g. `<s class="aside-left">some text</s>`, it is shown as ~~strike-through text~~. `<aside>` works as inside right side. Not sure if that is intended.

**To Reproduce**
Just write the above mentioned example.

**Expected behavior**
I expect the "aside" function to work as explained in the guidelines.

**Version [Desktop or Mobile]:**
Win 11, Obsidian v0.12.19, latest sanctum

**Comment by jdanielmourao** [comment]
Hi! The code you wrote works for me. Are you perhaps using the Smart Typography plugin? It can replace your quotation marks for curly ones, breaking the html syntax.

**Comment by shiMusa** [comment]
Yes, that was it! Thank you so much!
