### ISSUE TITLE
`<s class="aside-left">` overflows into main text

### ISSUE THREAD

**Issue by shiMusa** [jdanielmourao/obsidian-sanctum#50]
**Describe the bug**
Text in left aside overflows into main text

**To Reproduce**
make a left-aside html element

**Expected behavior**
Do not flow into main text

**Screenshots**
![image](https://user-images.githubusercontent.com/17574234/142932822-e9cf2a78-b5aa-4ce4-aecf-f10a80b0f61f.png)

**Version [Desktop or Mobile]:**
latest Obsidian, latest Sanctum

**Comment by jdanielmourao** [comment]
Does this happen with any the recommended fonts as well (iA Writer & IBM Plex)?

**Comment by shiMusa** [comment]
Just changed back to default fonts. Still there:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/17574234/143144188-be15f070-4346-48e8-a104-46e28e612b1e.png">

**Comment by shiMusa** [comment]
PS: I'm on Windows, so it's IBM Plex

**Comment by jdanielmourao** [comment]
Do you have any active snippets or external plugins? I'd recommend to disable them 1 by 1.

**Comment by shiMusa** [comment]
Deactivated all community plugins (safe mode on). Still there:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/17574234/143285974-afa14d56-4dbc-43a0-a440-e7979a947446.png">

**Comment by jdanielmourao** [comment]
Do you have any snippets affecting padding or readable line length perhaps?

**Comment by jdanielmourao** [comment]
If you changed line width in the Style Settings, that might be affecting it.

**Comment by jdanielmourao** [comment]
I've managed to finally reproduce this. It will be fixed next update.

**Comment by jdanielmourao** [comment]
This should now be fixed with the new update. :)
