### ISSUE TITLE
Implement app icons for links

### ISSUE THREAD

**Issue by vkbytes** [jdanielmourao/obsidian-sanctum#51]
**Is your feature request related to a problem? Please describe.**
Implementing app icons for links. When you add a link in a note, appending the app svg icon `::before` the link can be very fancy and neat

**Describe the solution you'd like**
This is implemented in the ITS Theme and also in Spectrum theme. Making this a native part of the sanctum theme will be awesome.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/79217316/143176547-07bf1986-1f6f-4fe5-8a0d-3b1b1b8f6a63.png">

**Comment by jdanielmourao** [comment]
Hi! That's already a feature of the theme, although the list of supported websites isn't as extensive as ITS.
This the the list of currently supported links
<p align=left><img src="https://user-images.githubusercontent.com/91087143/143249085-bc64c9d8-f1d3-438b-b782-5f4d44afa267.png" alt="Variable Headings" width=30% </p>
If you do have suggestions for more, I can always add them.

**Comment by vkbytes** [comment]
Oh I'd love to see support Notion, Amazon, AWS, Google, Microsoft, Shopify, Apple, Linux. This will be so cool if you could keep adding new apps to this workflow. Btw do you have a ko-fi or Github sponsors link for yourself?

**Comment by jdanielmourao** [comment]
I'll add your suggestions to the roadmap! I haven't been adding any more because I'm focused on the upcoming update, where I basically reorganize the entire css and clean it up, as well as improving the mobile version. As for ko-fi/sponsor links, if you want to support me, you can follow the links on this repo's "Sponsor" button, at the top right of the page.

**Comment by jdanielmourao** [comment]
With the coming of a new plugin (https://github.com/joethei/obsidian-link-favicon), I'll be "discontinuing" this feature, and add support to the plugin. So, basically, I'll be able to replace icons more easily and you'll be able to get a favicon for every link. :)
