### ISSUE TITLE
[BUG] Spaced Repetition Plugin, Deck Dropdown not visible

### ISSUE THREAD

**Issue by Mocca101** [jdanielmourao/obsidian-sanctum#53]
**Describe the bug**
When using the Theme, the Dropdown button for Subdecks is not visible/clickable. Thus preventing me from expanding a Deck to it's subdecks.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Install the Spaced Repetition Plugin (https://github.com/st3v3nmw/obsidian-spaced-repetition)
2. Create a few flashcards, using nested Tags as Deck structure
3. Open the Flashcard Review (Per clicking on the icon on the left or per command "Review flashcards from all notes")
4. Only base Tag is shown without the option to expand

**Expected behavior**
The expand button is visible and clickable.

**Screenshots**
In Snactum:
![image](https://user-images.githubusercontent.com/49754596/143315267-fe733763-eed6-4d7a-911c-ac17e577ee52.png)

In Obsidian Standard Theme:
![image](https://user-images.githubusercontent.com/49754596/143315329-ce32c679-41ff-4f32-bf97-8d95ae9f229c.png)
Expanded:
![image](https://user-images.githubusercontent.com/49754596/143315360-fcb21e2d-93a6-4759-aa47-6c5a248ab13d.png)

**Version [Desktop or Mobile]:** Desktop

**Additional context**
Using the latest Insider build (0.13.5).

**Comment by jdanielmourao** [comment]
Hi! I have a suspicion about what might be doing that, and should be out next update. Either way, it's been added to the Roadmap!

**Comment by Mocca101** [comment]
Thank you!

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by Mocca101** [comment]
Yes, it works perfectly now, thank you!
