### ISSUE TITLE
[BUG] Long Popup URLS overflow the popup

### ISSUE THREAD

**Issue by agryson** [jdanielmourao/obsidian-sanctum#55]
**Describe the bug**
Long urls can overflow in the tooltip, overflowing the container

**To Reproduce**
1. Create a (long) link to an external page `[link](http://long-link.com?reallylongparamaterhere)`
2. Switch to View Mode
3. Hover over the link

**Expected behavior**
The long url should wrap to be contained in its popup. 

**Screenshots**
In another theme it works fine:
![image](https://user-images.githubusercontent.com/1445853/143590732-5f910a77-4137-4f6f-93a0-42c346889a70.png)

In Sanctum it looks like this:
![image](https://user-images.githubusercontent.com/1445853/143592163-21690cf5-42cc-442b-befd-a8876f21e52a.png)

**Version [Desktop or Mobile]:** Desktop

**Additional context**
I was able to workaround this by creating this css snippet:
```css
.tooltip {
    overflow-wrap: break-word;
}
```

This snippet turns the Sanctum popup into this:
![image](https://user-images.githubusercontent.com/1445853/143592545-d462abc9-2c36-44ed-b9f4-2f4ff123cde8.png)

Which fixes the issue for me.

**Comment by jdanielmourao** [comment]
I've added it to the roadmap and a fix should ship next update. I also noticed this issue, but was wondering why it happened, seeing that I hadn't edited the tooltips that hard.

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by agryson** [comment]
I can confirm the issue is fixed now for me after removing my workaround snippet.
(and some nice icons added for google drive links now!)
