### ISSUE TITLE
[BUG] Custom Fonts Don't Work With Live Preview/Mobile

### ISSUE THREAD

**Issue by joelberger76** [jdanielmourao/obsidian-sanctum#56]
**Describe the bug**
Custom edit mode fonts are not respected with Live Preview enabled or on Mobile.

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. Enable Live Preview within the Editor settings pane (Desktop)
2. Restart Obsidian
3. Go to Style Settings -> Typography -> Fonts
4. Add a custom font as the first value of "Edit Mode Font"
5. Verify that this font is not utilized within Live Preview or Mobile in Edit mode
6. Disable Live Preview within the Editor settings pane (Desktop)
7. Restart Obsidian
8. Notice that the font is available on Desktop with Live Preview disabled in Edit mode

**Expected behavior**
Custom fonts should be available for use in the editor

**Version [Desktop or Mobile]:**
Desktop: Obsidian 0.13.6, iMac 2017 27", macOS 12.0.1
Mobile: Obsidian 1.0.5, iPhone 12 Pro, iOS 15.1.1

**Additional context**
I believe this is due to the utilization of CM6.  I've worked around this with the following snippet:
```css
.cm-line,
.markdown-source-view,
.cm-s-obsidian,
.cm-header { 
   font-family: 'MYFONT', monospace;
}
```

**Comment by jdanielmourao** [comment]
Hi! I'm still going over all the Live Preview changes, but some fixes will be out next update, that included.

**Comment by brimwats** [comment]
Seconding that this is still an issue for me

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by THeK3nger** [comment]
It has for me.

**Comment by brimwats** [comment]
confirmed!

**Comment by joelberger76** [comment]
Confirmed working for me as well - thank you!
