### ISSUE TITLE
[BUG] Settings modals overflow vertical monitors

### ISSUE THREAD

**Issue by brimwats** [jdanielmourao/obsidian-sanctum#57]
I think this is an easy fix (needs to be flex or something) but opening modals on settings breaks the modal:

![image](https://user-images.githubusercontent.com/49103046/143781122-aa7d962c-3975-4d89-85f8-043d22bc7d45.png)

**Comment by jdanielmourao** [comment]
I'm not sure what you mean by that. Do you get that when you open the settings modal?

**Comment by brimwats** [comment]
yep! I have it on a monitor that is vertical (so 1080x1920) and not horizontal (1920 x 1080)

**Comment by brimwats** [comment]
here's the relevant code:

```
.modal-container .modal.mod-community-theme:not(.is-mobile .modal.mod-community-theme),
.modal.mod-community-plugin:not(.is-mobile .modal.mod-community-plugin),
.modal.mod-settings:not(.is-mobile .modal.mod-settings) {
    width: 40vw;
    min-width: 1000px;
    height: 80vh;
    min-height: 80vh;
    max-height: 80vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    box-shadow: var(--elevation-1);
}
```

the min-width is the problem here

**Comment by jdanielmourao** [comment]
I've added it to the Roadmap, and will work on a fix!

**Comment by jdanielmourao** [comment]
Do you still get this error? The min-width is set to 1000px, so having a screen with 1080px width shouldn't be a problem... 🤔

**Comment by brimwats** [comment]
I do! it seems like it happens when I am zoomed in: 
![image](https://user-images.githubusercontent.com/49103046/144699429-b3dd5083-17f4-4899-a545-622f530318c3.png)

here are some other themes at the same zoom level:

california coast:
![image](https://user-images.githubusercontent.com/49103046/144699438-417e0ae6-f278-455e-bf82-6f6538ae3a2a.png)

obsidian you
![image](https://user-images.githubusercontent.com/49103046/144699445-ac393af3-3fd7-4b03-b2e5-c84d62d744a0.png)

shimmering focus, which also tries to compress and make the best use of space:
![image](https://user-images.githubusercontent.com/49103046/144699461-1b68393a-2112-4642-a9f3-598801e698b2.png)

**Comment by brimwats** [comment]
(ignore the rainmeter map widget at the bottom)

**Comment by jdanielmourao** [comment]
I've uploaded a fix for this. Min-width is now 800px, so  there shouldn't be a problem! :)
