### ISSUE TITLE
[BUG] Conflicts with Quick Explorer

### ISSUE THREAD

**Issue by brimwats** [jdanielmourao/obsidian-sanctum#58]
long folder/filename trails with [Quick Explorer](https://github.com/pjeby/quick-explorer) conflicts with statusbar in title—it looks like hiding the "obsidian" title would give you more space, as would shifting more to the right 

![image](https://user-images.githubusercontent.com/49103046/143781327-63bc1525-a230-4460-a02d-d1f5d5196a6d.png)

**Comment by brimwats** [comment]
(might have picked a bad demo image, but folders do eventually flow over—here's an example:
![image](https://user-images.githubusercontent.com/49103046/143781345-92e1831a-4d72-402b-9944-e142bb437cf3.png)

**Comment by jdanielmourao** [comment]
I'll add an option to hide the centered text for now.
