### ISSUE TITLE
[BUG] The plugin Metatable doesn't seems to be working with the Sanctum themes

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#59]
With only the metastable plugin toggle on, the YAML doesn't show, I have just the head of the note

It only happens with this theme. Both the theme and plugin are updated

I'm on desktop, running Linux Arch (DE: KDE) The package is installed through the AU
![Screenshoot 1](https://user-images.githubusercontent.com/79509045/143786181-8f2d35ce-f294-4fb7-9a91-cb2e3043d785.png)
![Screenshoot 2](https://user-images.githubusercontent.com/79509045/143786183-eb98ce0a-269a-48cf-89bd-8cc4c738f8f6.png)
![Screenshoot 3](https://user-images.githubusercontent.com/79509045/143786184-a3fd7d67-558a-4613-bd4e-7b271acf6187.png)
R

**Comment by jdanielmourao** [comment]
Use this as a snippet:
```
.markdown-preview-view .markdown-embed-title,
.markdown-preview-view .obsidian-metatable {
	display: visible;
}
```
That should fix it. I don't think you'll need the snippet next update btw!

**Comment by jdanielmourao** [comment]
Please confirm if the issue has been fixed! :)

**Comment by TRENEEDANAME** [comment]
It is now fixed, thank you very much !
