### ISSUE TITLE
[BUG] Relationship Lines in Edit Mode

### ISSUE THREAD

**Issue by vkbytes** [jdanielmourao/obsidian-sanctum#61]
**Describe the bug**
I see that I do not get the relationship Lines in the Edit mode. 

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. make sure you have relationship settings in the the theme set in Style settings

**Expected behavior**
I Wanted to have Relationship Line settings in the Edit mode like We have in the relationship lines in Other themes. I see by default we do not get relationship lines in Edit mode between bullet points

**Screenshots**
Edit Mode
![image](https://user-images.githubusercontent.com/79217316/143890375-11db54bf-c26a-4f18-a893-72490c1f647d.png)

Preview Mode
![image](https://user-images.githubusercontent.com/79217316/143890457-0f53d055-a38b-451a-b18f-3afaf471dd71.png)

**Version [Desktop or Mobile]:**
latest

**Additional context**

**Comment by jdanielmourao** [comment]
That is not a bug. I didn't add relationship lines in Edit Mode because they tend to be quite buggy, and I wanted to wait for Live Preview in order to see if I could come up with something decent that worked for both modes.

**Comment by vkbytes** [comment]
Got you, This sounds good. I'll wait till you add the feature to Edit Mode. Thanks for clarifying.
