### ISSUE TITLE
[BUG] word sprint start and stop buttons basically invisible 

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#62]
**Describe the bug**
There's no button anymore for the word sprint plugin

**To Reproduce**

Install word sprint plugin and use LP mode I guess. 

**Expected behavior**
I expect to be able to read the start and stop click things in word sprint plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/75856959/143965375-dd81e1c1-09fe-4319-bf60-3cf073c03947.png)

**Version [Desktop or Mobile]:**

Desktop

**Additional context**

v0.4

**Comment by jdanielmourao** [comment]
I think I missed the word-sprint scss module when replacing some css variables with new scss variables. Should be good now.

**Comment by eleanorkonik** [comment]
"stats" "goals" and "view stats' is still a different font but it's readable now thanks!

**Comment by jdanielmourao** [comment]
Oh, good catch! It's been fixed :)
