### ISSUE TITLE
[BUG] Setting window overlaps with iPhone status bar

### ISSUE THREAD

**Issue by THeK3nger** [jdanielmourao/obsidian-sanctum#63]
**Describe the bug**
The top bar of the setting (the one with the "x" to close it) overlap on the top status bar on my iPhone XR. As a consequence, I cannot close the settings.

**To Reproduce**
Open Obsidian's settings 

**Expected behavior**
The "x" should be lower. 

**Screenshots**

![image](https://user-images.githubusercontent.com/133159/144039493-b8fcd3ef-b51b-4f7d-a63c-0679b684f57d.jpeg)

**Version [Desktop or Mobile]:**
Mobile 0.4

**Comment by dancemonkey** [comment]
Hey you beat me to it, thanks for posting. I was also going to add a couple other niggling UI bits, I'll post a separate issue.

**Comment by jdanielmourao** [comment]
Have added it to the Roadmap.

**Comment by jdanielmourao** [comment]
I've uploaded a fix. Pls get back to me to see if the issue has been resolved!

**Comment by dancemonkey** [comment]
That did it for me (iOS), modals are close-able and I can see the sync indicator again.

**Comment by THeK3nger** [comment]
It works for me. Just to be super nit-picking, maybe the "X" should be slightly lower (aligned to "Setting"?). It will look more symmetric. But the specific issue of being unable to close the settings is solved. 😄 

![IMG_1694](https://user-images.githubusercontent.com/133159/144724668-23bac4aa-b9a2-4e73-87c3-efbcab354787.jpg)
.

**Comment by jdanielmourao** [comment]
It should have, but I must have changed things while iterating and forgot to center again 😅 It will get patched, don't worry.
