### ISSUE TITLE
[BUG] Ribbon is too tall for iPhone screen size, sync status icon missing?

### ISSUE THREAD

**Issue by dancemonkey** [jdanielmourao/obsidian-sanctum#64]
**Describe the bug**
The height of the ribbon (using the default Obsidian or Sanctum icons) is so tall it forces the "Settings" gear icon off the bottom of the window. 

I also can't locate the Sync status icon, it used to live in the slide-out right-hand pane next to the Pin and 3-dot menu icons, which are also both gone (or invisible, or moved?).

**Screenshots**

![ribbon](https://user-images.githubusercontent.com/9327646/144052935-7d383072-241d-4d74-9a37-63cfdc6b5c46.png)

![pane](https://user-images.githubusercontent.com/9327646/144052960-96f46edb-0c33-4b55-b1c6-2dbda3d7433f.png)

**Version [Desktop or Mobile]:**
Mobile, iOS 15.1.1, Obsidian 1.0.5

**Comment by jdanielmourao** [comment]
Have added it to the Roadmap

**Comment by jdanielmourao** [comment]
I've uploaded a fix. Please tell me if the issue is resolved.

**Comment by dancemonkey** [comment]
Sorry I missed this reply. The settings icon is still not visible in the ribbon, but the sync status icon is back (and more important imo, thank you).

**Comment by jdanielmourao** [comment]
I've made an update yesterday that should have fixed the ribbon!

**Comment by dancemonkey** [comment]
The settings gear is still a skoche cut off but I’m not picky.  Thanks again!
![B2C55971-6B60-47F6-8421-0CBFB0258E0C](https://user-images.githubusercontent.com/9327646/145055403-0b33b477-3852-483f-8478-db0c05a7bb76.jpeg)
