### ISSUE TITLE
Link icons too low

### ISSUE THREAD

**Issue by kmaustral** [jdanielmourao/obsidian-sanctum#65]
Thanks for the outstanding theme. 

![image](https://user-images.githubusercontent.com/73867063/144146698-6806f31b-a61f-4652-b872-30c40b706269.png)

Please excuse my pedantry, but it seems that the link icons are a couple of pixels misaligned. Would it be possible to give them a little lift so that they align with the block?

**Comment by kmaustral** [comment]
Thanks and congratulations on the well-deserved Obsidian October award.

Just one or two pixels, please! Just to align with the beautiful
checkboxes.


______________________

Melbourne, Narrm, Victoria, Australia

Gunyang 🌼 kangaroo apple season

🌘 Waning crescent moon

🗓️ Thursday 2 December 02021

*🌡️ *Humid. Sunny morning. High (80%) chance of showers, most likely
during this afternoon and evening. The chance of a thunderstorm during this
afternoon and evening, with possible hail and heavy falls. Winds north to
northeasterly 25 to 35 km/h becoming northerly 25 to 40 km/h during the
morning then shifting south to southwesterly 25 to 35 km/h in the late
afternoon. 31℃

😷 Number of COVID cases on ICU in Australia is 71, -0 from yesterday.

🤔 “If the beach is beautiful, the sea is the cause.” Ahmad Tamimi

**Comment by jdanielmourao** [comment]
With the coming of a new plugin that does exactly this (https://github.com/joethei/obsidian-link-favicon), I think I'll probably "discontinue" this as an in-built feature. I might change the plugin icons if I don't like what they look like, though. So, in the end, people will get a favicon in every link, and I can just replace them if I don't like them, without worrying about centering them each time. Centering 1 by 1 gets tiresome quickly. :)

**Comment by kmaustral** [comment]
Good call. I saw this and wondered if it would create double up with your
excellent theme.
