### ISSUE TITLE
Live Preview blockquotes not rendering [BUG]

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#66]
**Describe the bug**

only double-quotes are showing up in live preview? on base theme regular > get indicated:

**To Reproduce**

Format something with `>` in live preview. 

**Expected behavior**

some visual indicator that it's a blockquote

**Screenshots**

https://discord.com/channels/686053708261228577/702656734631821413/916543601129951242

**Version [Desktop or Mobile]:**

Desktop 

**Additional context**

You said: " I haven't changed them, so probably need updating"

**Comment by jdanielmourao** [comment]
I've pushed a quick update. For now regular ">" blockquotes seems to be a bit buggy, and don't show the entire border for some reason. If you use html tags, it should all work though.

**Comment by eleanorkonik** [comment]
I don't know what happened here o.o

![image](https://user-images.githubusercontent.com/75856959/144751015-49d3ce22-3659-438c-9466-50694dd6a446.png)

**Comment by jdanielmourao** [comment]
Hm...I think it might be best to drop the idea of LP blockquote blocks 😅

**Comment by eleanorkonik** [comment]
I think that's fair xD as long as there's some indication like in core I think it's fine 😂
