### ISSUE TITLE
[BUG] Plugin (Sliding Planes (Andy's Mode)) Compatibility Problem

### ISSUE THREAD

**Issue by HueDOTByte** [jdanielmourao/obsidian-sanctum#67]
**Describe the bug**
while stacking multiple panes, some panes (only the stacked one on the left side) get translucent (background)

**To Reproduce**
Steps to reproduce the behavior (this is an example):
1. open more than 2 files, while stacking the panesthe issue occours 

**Screenshots**
https://imgur.com/J0prTgN

**Version [Desktop or Mobile]:**
Desktop 

**Additional context**
see screenshot, should be enough to understand the issue

**Comment by jdanielmourao** [comment]
Pushed a fix
