### ISSUE TITLE
[BUG] checkbox toggle inside settings menu is not aligned

### ISSUE THREAD

**Issue by HueDOTByte** [jdanielmourao/obsidian-sanctum#68]
**Describe the bug**
> some checkbox toggle inside settings menu is not aligned
> see screenshot, should explain the issue

**Screenshots**
https://imgur.com/xCZPjYP

**Version [Desktop or Mobile]:**
Desktop

**Additional context**
-

**Comment by jdanielmourao** [comment]
Made a few tweaks to it, although sometimes it just seems like it misaligns sometimes.
