### ISSUE TITLE
[BUG] Custom checks don't render if you "break the chain" in a checklist

### ISSUE THREAD

**Issue by dancemonkey** [jdanielmourao/obsidian-sanctum#69]
**Describe the bug**
If you place an empty line at the end of a checklist with custom checks, then place another checklist item, all of the previous custom checks under that heading become standard-flavored checks. Screenshots attached. 

Placing a new heading or even just typing some text seems to allow you to start a new checklist with impunity (and keep the custom checks).

**Screenshots**

Markup
![image](https://user-images.githubusercontent.com/9327646/144904153-319543fb-8e05-45d2-9e54-86d09310564f.png)

Preview - A-OK
![image](https://user-images.githubusercontent.com/9327646/144904244-bf092074-3de5-432e-92eb-58d83d9cb8f2.png)

Add an EMPTY line and a new checklist item...
![image](https://user-images.githubusercontent.com/9327646/144904303-3b0a41fb-611e-47b1-9956-2eef9e5601de.png)

And we get...
![image](https://user-images.githubusercontent.com/9327646/144904343-2a4b082a-ee8c-40eb-bc2c-7afd7cf6c067.png)

**Version [Desktop or Mobile]:**
- Windows 10 and iOS

**Comment by dancemonkey** [comment]
And just to illustrate the stopgap fix, you can put text after the final item in the first list (a period even, but a spacebar isn't enough on its own):

![image](https://user-images.githubusercontent.com/9327646/144904755-eaec889f-7259-4381-bac6-d276d43bb95d.png)

**Comment by jdanielmourao** [comment]
I've made a quick update to fix it. It will still somewhat change the formatting of the admonitions, because Markdown treats it as a [loose list](https://spec.commonmark.org/0.30/#loose), and changes the html structure a bit, forcing the icons to be inside the backgrounds, which is a little odd. Regular task lists should work fine, though.

**Comment by dancemonkey** [comment]
Yes you did, that did it. Thank you!
