### ISSUE TITLE
 Place the collapse button where it belongs please

### ISSUE THREAD

**Issue by thephm** [jdanielmourao/obsidian-sanctum#71]
Please see: [Why let themes change a core navigation item in the ribbon bar?](https://forum.obsidian.md/t/why-let-themes-change-a-core-navigation-item-in-the-ribbon-bar/28440)

Would like to have the button at the top. I feel stupid for not seeing it at the bottom but I kept looking for it at the top especially because Obsidian help tells me it's there.

**Comment by owldown** [comment]
Installed on my iPad, the collapse button isn’t in the bottom either, and there is no way to collapse the left sidebar by swiping or through the command palette “Toggle left sidebar”. Maybe I’m missing something, but I’ve never seen a theme break that function before.

**Comment by jdanielmourao** [comment]
Hi @thephm !
As this is an intended feature of the theme, I won't be changing it anytime soon. Having it at the bottom enables me to completely remove the side ribbon which would only house the button itself, gaining screen real estate. 
I'm sorry about your experience, and by no means do I want to sound crass, but if you would like a theme that doesn't do this, you are free to choose one that better suits your needs, or maybe even use a css snippet to change that in the theme (Sanctum isn't the only one that does this, so the tip applies to other themes as well).

Hi @owldown ! 
There's no collapse button for the sidebars in the mobile version. By default in obsidian, you can collapse the bars by swiping. The theme does not affect that action, so there might be something going on in your end.

**Comment by owldown** [comment]
I think I might have figured out my issue, but it still seems like something you might want to address: I had the left sidebar pinned, and then selected your theme. Your theme has no affordance for unpinning because your theme is intended to always show it. This left a situation where it was just stuck. There also doesn’t seem to be a command to unpin the sidebar (or at least I couldn’t find one). I don’t know if this is possible, but if you didn’t want to change the UI, maybe there is some way that switching to your theme would unpin the sidebar?

Having the sidebar take up so much of the screen constantly made me immediately dismiss your theme, but I’m interested in taking another look now that I know what’s up.

**Comment by jdanielmourao** [comment]
@owldown May I ask why pin it? Doesn't it get on top of the note?

**Comment by owldown** [comment]
On other themes, when I pin the side bar, it doesn’t cover the note, but is next to the other note panes (and taking up less of the screen than your theme). But what was messed up for me was that pinning the left sidebar and then enabling your theme leaves the left sidebar stuck taking up about 1/3 of the ipad screen with no way to hide or dismiss it. 

Oddly, your theme *does* allow unpinning the right sidebar if it was already pinned when switching to your theme (but no way to re-pin it). If that were true for the left sidebar also there wouldn’t be a problem (which is a minor problem and now I know the workaround).

**Comment by jdanielmourao** [comment]
@owldown Thanks for the feedback, I'll look into it! :)

**Comment by jdanielmourao** [comment]
@owldown I think I've found a solution to show the unpin icon if the panel is already pinned, and make it disappear once it's unpinned. Will release next update. ;)

**Comment by jdanielmourao** [comment]
@thephm I've been iterating somewhat of a compromise solution: having the left panel collapse indicator in the default position, and the right one at the bottom. Do you think that setup would be preferable?

**Comment by thephm** [comment]
thanks so much for looking into that? oh gosh, that's a good question. I would say leave them at the same relative position, both at the bottom or both at the top but I really appreciate you working on it. I have an idea for a related improvement I will submit.
