### ISSUE TITLE
The ordered list is not viewable on IdeaPad Duet [ChromeOS]

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#73]
The ordered list works in Edit mode, not in Preview mode, the number are on the border

![Screenshot 2021-12-17 13 54 25](https://user-images.githubusercontent.com/79509045/146547640-71e8c693-57bf-46a2-b517-680f6e247362.png)
![Screenshot 2021-12-17 13 54 10](https://user-images.githubusercontent.com/79509045/146547645-12dc45de-e969-4cf2-a761-cfc23c37a5d0.png)

**Comment by jdanielmourao** [comment]
Hi! Could you please send me new screenshots? I'm unable to fully understand what you mean by the ones you provided. 🤔

**Comment by TRENEEDANAME** [comment]
> Hi! Could you please send me new screenshots? I'm unable to fully understand what you mean by the ones you provided. thinking

Hello, in the Edit mode (I'm talking about the legacy editor), the ordered list looks normal, but in Preview mode, the ordered list is in the "border" of the screen, the numbers are in the border and thus not viewable.

I hope this could help, you can ask if my explication is still bad.

**Comment by jdanielmourao** [comment]
Unfortunately I'm unable to reproduce this in my end. I recommend disabling any plugins and snippets you might have enabled. If the problem persists, you can try pressing `Ctrl+Shift+I` to open Dev Tools, then click the top left icon in Dev Tools (if you hover it, it will say something like "Select an element in the page to inspect it"), and click the marker/list. Then take a screenshot of the code that shows.

**Comment by TRENEEDANAME** [comment]
> Unfortunately I'm unable to reproduce this in my end. I recommend disabling any plugins and snippets you might have enabled. If the problem persists, you can try pressing `Ctrl+Shift+I` to open Dev Tools, then click the top left icon in Dev Tools (if you hover it, it will say something like "Select an element in the page to inspect it"), and click the marker/list. Then take a screenshot of the code that shows.

I use the Android app

**Comment by jdanielmourao** [comment]
I'm sorry, but I don't think I have a way of effectively troubleshooting for your edge case. I've made a few hotfixes since, so I advise you to try and update the theme, to see if the issue is resolved.

**Comment by jdanielmourao** [comment]
The issue has been fixed, as per feedback of the user: https://github.com/jdanielmourao/obsidian-sanctum/issues/108#issuecomment-1006850712
