### ISSUE TITLE
File explorer appears broken on macOS

### ISSUE THREAD

**Issue by hinnerk** [jdanielmourao/obsidian-sanctum#74]
Given a folder with ~280 files, scrolling through it the file explorer at some point only shows empty space instead of the expected file list. The point where the list stops showing randomly moves. It shows shuffling of file names while scrolling.

**To Reproduce**
1. Given bash, in the vault, do:
2. `mkdir Test`
3. `touch Test/{1..200}-{bla,blupp,foo,bar,bozz,bazz,duzz,dazz}.md`
4. expand "Test" folder in the file explorer, scroll to where it stops working, notice the file name
5. close and re-open folder, scroll, for me it stops working at a different file.

Tested in an iCloud vault as well as in a local vault.

**Expected behavior**

Should list files as quickly as other themes do. I validated that this works well with the default theme.

**Screenshots**

<img width="335" alt="Bildschirmfoto 2021-12-18 um 12 29 01" src="https://user-images.githubusercontent.com/24145/146639366-18f8511a-659e-4c1e-874d-b6c8decbda2a.png">

**Version [Desktop or Mobile]:**

- Obsidian 0.12.19
- current Sanctum theme
- macOS Big Sur 11.6.1

**Comment by jdanielmourao** [comment]
Thanks for the detailed post! I was able to replicate the issue, and will look into it! I've added it to the Roadmap, in case you want to follow on its progress.

**Comment by eleanorkonik** [comment]
Came here to report this is happening to me on Windows and found this issue. In case it helps, here's another gif.
![folders-not-loading](https://user-images.githubusercontent.com/75856959/147173253-4d6cd723-8084-4bb8-8dfb-4be5f88f0dac.gif)

**Comment by jdanielmourao** [comment]
Just pushed a fix for this! Should now work normally. :)
