### ISSUE TITLE
Control of Background Color

### ISSUE THREAD

**Issue by ackstorm23** [jdanielmourao/obsidian-sanctum#75]
- I prefer the background color of the app to be pure black, but this is not something that  can be changed in style settings.
- I've been making my own copy of the theme where I change the background color to black but then I have to keep merging in your updates.

**Comment by jdanielmourao** [comment]
If you look at the [Roadmap](https://github.com/jdanielmourao/obsidian-sanctum/projects/1), you'll find that there's a True Black Dark Mode in the works.
