### ISSUE TITLE
[BUG] LaTex does not take the proper size, same for underline text

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#77]
**Describe the bug**
LaTex works perfectly, but, when inside a title, the LaTex formulas are at the base size

**Expected behaviour**
LaTex should take the same size as the heading it is in

**Screenshots**

#### The new Live preview mode : view
![image](https://user-images.githubusercontent.com/79509045/147211586-a1c74fd8-5926-475f-b115-f3401203629b.png)

#### The new Live preview mode : edit
![image](https://user-images.githubusercontent.com/79509045/147211686-bd5ee6ad-8b02-4ea3-83c8-68061725bc81.png)

#### The Legacy mode : view
![image](https://user-images.githubusercontent.com/79509045/147211872-d485d4cb-97b0-4129-8380-60f537c8ac94.png)

#### The view Legacy mode works fine

**Version [Desktop or Mobile]:**
Desktop (Linux version) and Android version

---

# Underline
Same as LaTex

#### Legacy : edit
![image](https://user-images.githubusercontent.com/79509045/147212021-af758e67-ba85-44f7-813d-db20496f0d57.png)

#### Live mode : view
![image](https://user-images.githubusercontent.com/79509045/147212313-c8fee656-83a2-49cb-94ba-8fd4e13393e1.png)

#### Live mode : edit
![image](https://user-images.githubusercontent.com/79509045/147212358-0dbd973f-13b6-4381-972c-878bac669b0f.png)

**Comment by jdanielmourao** [comment]
Hi! Just want to say that I managed to reproduce the issue, and have worked on a fix. It will be released next update. :)

**Comment by jdanielmourao** [comment]
This should now be fixed with the new update! :)
