### ISSUE TITLE
[BUG] UP/DOWN arrows indicate different spacing

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#80]
**Describe the bug**
Down vs. Up arrows go up and down a different number of times, so basically it seems going in one direction that there isn't a blank line between lines, but in the other direction there IS a blank line. 
![down-down-up-up](https://user-images.githubusercontent.com/75856959/147238975-76ea5397-e132-4596-8bf1-e5c92cbf117b.gif)

**Expected behavior**
On the base theme, I can do the same number of up arrows and down arrows.

**Version [Desktop or Mobile]:**

Desktop

**Additional context**

This is making it really hard for me to tell what my spacing is in Live Preview.

**Comment by jdanielmourao** [comment]
Reminder: This has been closed because the user didn't report the error again. Will open if it happens again.
