### ISSUE TITLE
[BUG] Floating preview/edit mode button on mobile gone

### ISSUE THREAD

**Issue by dancemonkey** [jdanielmourao/obsidian-sanctum#81]
**Describe the bug**
The latest update killed the floating edit/preview button on mobile, it’s returned to the page header bar. 

**Version [Desktop or Mobile]:**
Mobile, iOS.

**Comment by jdanielmourao** [comment]
Interesting, when I emulate mobile in obsidian, it shows the button, but when I try it on mobile I can reproduce the same error... 🤔I'll look into it!

**Comment by dancemonkey** [comment]
Not a huge issue, but I’d really gotten used to the convenient placement!

**Comment by jdanielmourao** [comment]
Issued a fix, hopefully it works now. The element targetting stopped working with the new updates to obsidian, so I had to resort to something different.

**Comment by dancemonkey** [comment]
That did it for me, thank you and happy holidays!

**Comment by jdanielmourao** [comment]
Great! Happy holidays! :)
