### ISSUE TITLE
[BUG] Weird glowy white line on mobile

### ISSUE THREAD

**Issue by dancemonkey** [jdanielmourao/obsidian-sanctum#82]
**Describe the bug**
The latest update added a glowy white bar across the top of the note (and in other places). Edit and preview modes, also showing in sidebar views. 

**Screenshots**
![855CE70C-0A67-4676-98A2-2C1B944141E6](https://user-images.githubusercontent.com/9327646/147297983-63ed3ae7-7c62-42f4-9386-dfb13a520739.jpeg)
![2F6148DF-EB46-4A39-8E17-C8A37ABBA2D4](https://user-images.githubusercontent.com/9327646/147297984-83b1efbd-8ea6-4839-b857-0e9d7743c712.jpeg)

**Version [Desktop or Mobile]:**
Mobile, ios

**Comment by jdanielmourao** [comment]
Could you try updating again? I pushed a hotfix I think might help.

**Comment by dancemonkey** [comment]
The line went away after updating the theme, but then when I navigated to another note and back it showed up again. I tried changing themes back and forth and that didn’t work. Also deleted and reinstalled theme and it’s still there. 

Also it shows up on the breadcrumbs panel only, not any of the other sidebar panels (sidebar, dice roller, outline, etc).

**Comment by jdanielmourao** [comment]
> The line went away after updating the theme, but then when I navigated to another note and back it showed up again. I tried changing themes back and forth and that didn’t work. Also deleted and reinstalled theme and it’s still there.
> 
> Also it shows up on the breadcrumbs panel only, not any of the other sidebar panels (outline, dice roller, backlinks, etc).

That is very strange that it only shows in the breadcrumbs panel. 🤔 So does it now only show in that Matrix relationship real/implied section?

**Comment by dancemonkey** [comment]
Sorry, to be clear, it shows in the main window still too AND on the breadcrumbs panel, but that’s the only slide-out pane where it shows up. But yes it shows in the same areas in my original screenshots.

**Comment by jdanielmourao** [comment]
Does it only happen in dark mode? Also, I've made some small changes, perhaps they'll help.

**Comment by dancemonkey** [comment]
Oh good question. It now is not happening at all anyway, so it appears your changes got it (at least for me). Thanks again!

**Comment by jdanielmourao** [comment]
That's good to know! Happy Holidays! :)
