### ISSUE TITLE
Inconsistency with - [n]

### ISSUE THREAD

**Issue by eleanorkonik** [jdanielmourao/obsidian-sanctum#83]
![image](https://user-images.githubusercontent.com/75856959/147298672-5ea59eaf-f356-4963-ae7c-21df09fb615a.png)

These are next to each other so I guess it's causing some kind of weirdness with the hanging indent? 

But these are also next to each other and instead of the weird hanging indent it's getting weird line spacing: 

![image](https://user-images.githubusercontent.com/75856959/147298720-9a6b4cc7-ab40-4454-895c-ce4e1eef8430.png)

Windows laptop, Sanctum 0.0.5

In case I forget later and you need the repro file, it's Against the Grain notes 2021-12-22

**Comment by jdanielmourao** [comment]
Fixed! :)
