### ISSUE TITLE
[BUG] Line Spacing Issue

### ISSUE THREAD

**Issue by MESMUR** [jdanielmourao/obsidian-sanctum#84]
**Describe the bug**
There is a significant difference between the placement of the cursor on the screen and the actual line that is highlighted. 

I do not think this is a repeat of #80 because the number of lines moved is not the issue. You can see from the recording that I only move one line at a time but the placement is still messed up (I am sorry if it is a duplicate though, feel free to close).

**To Reproduce**
Recording below, something in the newest update must be the reason because this issue only appeared when I updated.

**Expected behavior**
Cursor placement on the editor and the _actual_ line that is highlighted should be the same.

**Screenshots**

![line_bug](https://user-images.githubusercontent.com/22883661/147307847-c3d992f9-28c1-46da-8593-7c5ac63b929f.gif)

**Version [Desktop or Mobile]:**
Desktop

**Additional context**
I am using the legacy editor in the newest obsidian version.

**Comment by jdanielmourao** [comment]
Thanks for reporting this, this is really strange behaviour. I'll look into it!

**Comment by jdanielmourao** [comment]
Are you using the legacy editor? If so, I've pushed a hotfix that should resolve this issue!

**Comment by MESMUR** [comment]
I am! Tested it just now, no issue for me ;)
Thank youu~!

**Comment by jdanielmourao** [comment]
Great! I'll go ahead and close the issue. :)
