### ISSUE TITLE
## is no different than #

### ISSUE THREAD

**Issue by DeutscheGabanna** [jdanielmourao/obsidian-sanctum#85]
There is no visible change in appearance between H2 and H1. They look the same in both live preview, source mode and read mode. I tried updating the theme.

**Comment by jdanielmourao** [comment]
It might be that there aren't enough imported weights for IBM Plex to work on headings currently. I have the font installed on my system, so I wouldn't notice. Could you please try changing the heading font to `iA Writter Quattro S` in Style Settings?

**Comment by Manifaust** [comment]
I think I also see the same issue. I enabled `IBM_Plex_snippet.css` and I took a screen shot.

<img width="757" alt="Screen Shot 2021-12-30 at 11 34 49 AM" src="https://user-images.githubusercontent.com/175788/147770808-e54f719a-4429-45a8-9c5e-93ffdc40c771.png">

**Comment by jdanielmourao** [comment]
> I think I also see the same issue. I enabled `IBM_Plex_snippet.css` and I took a screen shot.
> 
> <img alt="Screen Shot 2021-12-30 at 11 34 49 AM" width="757" src="https://user-images.githubusercontent.com/175788/147770808-e54f719a-4429-45a8-9c5e-93ffdc40c771.png">

It's supposed to be the same size, but different weights. It's how I made the headings when the theme first came to existence. It might change in the future however. If you'd like to have more control on the size, you can toggle Productive Headings option in Style Settings and specify each size and weight of each heading.
