### ISSUE TITLE
[IDEA/REQUEST] custom colors for yaml

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#93]
**Is your feature request related to a problem? Please describe.**
To make yaml more visible and easier to work with.

**Describe the solution you'd like**
It would be nice if there was one color for the property and one for the value. If we can customize each one, even better.

**Additional context (example)**
![image](https://user-images.githubusercontent.com/38974541/147888042-ea3dddb6-d1c0-45df-a222-1eb8ecf9af66.png)

**Comment by jdanielmourao** [comment]
That can easily be added, even though YAML will be reworked in the near future, according to Obsidian's Roadmap.

**Comment by imeed166** [comment]
Really ? didn't know.

**Comment by jdanielmourao** [comment]
Yeah. This is an easy enough thing to do, though!
