### ISSUE TITLE
[IDEA/REQUEST] customize bullet point icons

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#94]
**Is your feature request related to a problem? Please describe.**
I would like to set my icons, and if possible disable the alternating icons for each level of indentation.

**Describe the solution you'd like**
1. multiple options of icons to choose from 
2. toggle to enable/disable alternating between different icons based on level of indentation.

**Comment by jdanielmourao** [comment]
I like the idea, but will keep it at the back of the Todo list for the time being.
