### ISSUE TITLE
[IDEA/REQUEST] checkbox color customization

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#95]
**Is your feature request related to a problem? Please describe.**
I would like to change the color of the checkbox when completed. And the hover color also

**Describe the solution you'd like**
If I could change the completed checkbox and hover color from yellow to a custom color, that would be enough.

**Comment by jdanielmourao** [comment]
The current hover colour is green, although it's a very warm apple green. I can add an option for it, though.
