### ISSUE TITLE
[IDEA/REQUEST] dataview table width in preview mode

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#97]
**Is your feature request related to a problem? Please describe.**
Dataview tables take only the space they need in preview mode. For symmetry, I would like for them to have the same width (max width of pane) just like it is in the live preview mode.

**Describe the solution you'd like**
A toggle from default to max width.

**Comment by jdanielmourao** [comment]
They aren't like that by default because if they need more space, they can occupy more than 100%, which isn't possible if I fix it at 100%. Having said that, I can add an option to force them to occupy the full width of the pane (off by default).

**Comment by imeed166** [comment]
Yes, this option would be much appreciated.
