### ISSUE TITLE
[IDEA/REQUEST] live preview mode line width

### ISSUE THREAD

**Issue by imeed166** [jdanielmourao/obsidian-sanctum#98]
**Is your feature request related to a problem? Please describe.**
I would like to adjust the width just like in the preview mode with this slider
![image](https://user-images.githubusercontent.com/38974541/147888728-6488ab91-1b0e-4a36-8b70-7399532c4866.png)

**Describe the solution you'd like**
A slider to adjust line width in live preview mode.

**Comment by jdanielmourao** [comment]
I haven't checked line width settings since the new Live Preview update. I'll need to check out obsidian's CSS to see if it's still possible, and what's the best way to do it.

**Comment by jdanielmourao** [comment]
Just wanted to let you know that there will be a Style Settings option for Readable Line length (common to both Reading and Editing View) in the next version of Sanctum. You can expect to see it available when Obsidian 0.16.x launches, or in case you have an insider license, today. :)
